<?php

namespace App\Console\Commands;

use DOMDocument;
use Illuminate\Console\Command;

class Test extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 't';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $this->info('Hello World');

        $categories = $this->getCategories();

        dd($categories);

    }


    public function getCategories()
    {
        return [
            [ 'l1' => 'Antiques, Collectibles & Gifts',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Antiques',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Coins and Paper Money',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Gifts',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Sovenirs',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Sports Memorabilia',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Stamps',],
            [ 'l1' => 'Antiques, Collectibles & Gifts', 'l2' => 'Other Collectibles',],
            [ 'l1' => 'Baby, Pregnancy & Maternity',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Baby Carriers & Backpacks',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Baby Shoes',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Baby Toys',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Bathing & Grooming',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Clothing & Accessories',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Diapering',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'Bibs',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'Bottles',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'Breast Pumps',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'High Chairs',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'Plates, Bowels & Cups',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'Sterilisers & Food Warmers',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Feeding', 'l3' => 'Other',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Furniture & Bedding',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Health & Baby Care',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Maternity',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Nursery Decor',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Pregnancy',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Strollers & Walkers',],
            [ 'l1' => 'Baby, Pregnancy & Maternity', 'l2' => 'Other Baby Products',],
            [ 'l1' => 'Books & Magazines',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Children & Babies',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Children & Babies', 'l3' => 'Activity & Colouring',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Children & Babies', 'l3' => 'Educational',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Children & Babies', 'l3' => 'Other',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Comics',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Fiction',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Magazines',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Non-Fiction',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Textbooks',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Young Adult Fiction',],
            [ 'l1' => 'Books & Magazines', 'l2' => 'Other',],
            [ 'l1' => 'Clothing & Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Athletic & Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Hoodies & Sweater',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Jackets & Coats',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'School Uniforms',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Shirts & T-Shirts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Shorts & Beachwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Sleepwear & Lounge',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Socks',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Underwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Clothing', 'l5' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'Athletic & Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'Flip Flops',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'Loafers & Slip-Ons',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'Sandals',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'School Shoes',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'Sneakers',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Footwear', 'l5' => 'Other Footwear & Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Hats & Caps',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Boys', 'l4' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Athletic & Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Dresses & Skirts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Hoodies & Sweater',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Jackets & Coats',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Jeans & Pants',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Leggings',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'School Uniforms',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Shirts, T-Shirts & Tops',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Shorts & Beachwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Sleepwear & Lounge',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Socks',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Underwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Clothing', 'l5' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Athletic & Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Flats',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Flip Flops',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Loafers & Slip-Ons',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Sandals',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'School Shoes',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Sneakers',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Footwear', 'l5' => 'Other Footwear & Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Hair Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Hats & Caps',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Jewelry',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Girls', 'l4' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Costumes',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'School Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Sunglasses',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Watches',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Men',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Athletic & Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Flip Flops',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Formal Shoes & Boots',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Loafers & Slip-Ons',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Sandals',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Sneakers',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Other Footwear & Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Belts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Bracelets & Wristbands',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Cufflinks',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Handkerchiefs',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Hats & Caps',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Necklaces, Rings & Earrings',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Ties',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Wallets',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Accessories', 'l4' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Athletic and Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Beachwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Hoodies & Sweater',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Jeans',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Pants',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Shirts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Shorts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Sleep & Lounge',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Socks',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'T-Shirts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Underwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Men Clothing', 'l4' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Women',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Athletic & Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Flats',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Flip Flops',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Formal Shoes & Boots',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Heels',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Loafers & Slip-Ons',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Sandals',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Sneakers',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Footwear', 'l4' => 'Other Footwear & Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Belts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Bracelets',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Burugaa Dathi and Pins',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Earrings',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Fashu Foo',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Hair Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Handbag & Purse',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Hats & Caps',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Necklaces',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Rings',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Accessories', 'l4' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Athletic and Sports',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Beach and Swimwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Bras',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Buruga & Shawl',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Dresses',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Hoodies & Sweater',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Jeans',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Kurutha and Tops',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Leggings',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Lingerie & Shapewear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Panties',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Pants',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Shorts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Skirts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Sleepwear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Socks & Tights',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'T-Shirts',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Women Clothing', 'l4' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Sunglasses',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Travel & Bags',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Backpacks',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Briefcases',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Gym Bags',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Luggage & Travel Bags',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Messenger Bags',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'School Bags',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Travel Accessories',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Umbrellas & Rain Wear',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Waist Packs',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Kids', 'l3' => 'Other',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Watches',],
            [ 'l1' => 'Clothing & Accessories', 'l2' => 'Other Clothing & Accessories',],
            [ 'l1' => 'Computer, Tablets & Networking',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Card Readers & USB Hubs',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage', 'l4' => 'DVD & CD Drives',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage', 'l4' => 'Hard Drives - External',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage', 'l4' => 'Hard Drives - Laptop',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage', 'l4' => 'Hard Drives- Internal',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage', 'l4' => 'Pen Drive',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Drives & Storage', 'l4' => 'Other',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Graphics Cards',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Keyboards, Mouse & Input Devices',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Keyboards, Mouse & Input Devices', 'l4' => 'Keyboards',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Keyboards, Mouse & Input Devices', 'l4' => 'Mouse',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Keyboards, Mouse & Input Devices', 'l4' => 'Mouse & Keyboard Bundles',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Keyboards, Mouse & Input Devices', 'l4' => 'Other',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Memory',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Memory', 'l5' => 'Laptop Memory',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Memory', 'l5' => 'PC Memory',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Monitors',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Motherboard',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Power Supplies',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Processor',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Projectors',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Sound Card',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Speakers & Headphones',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Webcams',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Accessories & Parts', 'l3' => 'Other Accessories',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Desktop',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories', 'l3' => 'Battery',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories', 'l3' => 'Carrying Cases and Bags',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories', 'l3' => 'Charger',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories', 'l3' => 'Cooling Pad',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories', 'l3' => 'Power Adapter',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Laptop Accessories', 'l3' => 'Other',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Modems',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Routers & Switches',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Servers',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Wireless Networking',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Wireless Networking', 'l4' => 'Accessories and Parts',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Wireless Networking', 'l4' => 'Bluetooth',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Wireless Networking', 'l4' => 'Mobile Modem',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Wireless Networking', 'l4' => 'Routers and Access Points',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Wireless Networking', 'l4' => 'USB Dongles',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Networking', 'l3' => 'Other',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Printer Supplies & Accessories',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Printers & Scanners',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Software',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Tablet Accessories',],
            [ 'l1' => 'Computer, Tablets & Networking', 'l2' => 'Tablets',],
            [ 'l1' => 'Dhoani, Boats & Fishing',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC', 'l3' => 'Dhoani',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC', 'l3' => 'Dinghies & Bokkura',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC', 'l3' => 'Jet Ski / PWC',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC', 'l3' => 'Passenger & Safari Boats',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC', 'l3' => 'Speedboat',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Dhoani, Boats & PWC', 'l3' => 'Other Marine Vessels',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Fish Finders',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Fishing Line',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Lures and Hooks',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Reels',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Rods',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Rods and Reels',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Vadhu Foshi',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Fishing', 'l3' => 'Other',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Marine Engines & Parts',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Marine Engines & Parts', 'l3' => 'Engines',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Marine Engines & Parts', 'l3' => 'Parts & Accessories',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Anchors',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Buoys & Fenders',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Lifejackets',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Navigation Equipment',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Propellers',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Safety',],
            [ 'l1' => 'Dhoani, Boats & Fishing', 'l2' => 'Parts & Accessories', 'l3' => 'Other',],
            [ 'l1' => 'Electronics',],
            [ 'l1' => 'Electronics', 'l2' => 'Batteries & Chargers',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Digital Camera',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Binoculars & Telescopes',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camcorders',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Drone',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Battery and Charger',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Cases and Bags',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Flashes',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Lenses',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Photo Studio Supplies',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Tripods & Monopods',],
            [ 'l1' => 'Electronics', 'l2' => 'Camera, Photo & Video', 'l3' => 'Camera Accessories', 'l4' => 'Other Accessories',],
            [ 'l1' => 'Electronics', 'l2' => 'Electronic Components & Supplies',],
            [ 'l1' => 'Electronics', 'l2' => 'Electronic Components & Supplies', 'l3' => 'Active Components',],
            [ 'l1' => 'Electronics', 'l2' => 'Electronic Components & Supplies', 'l3' => 'Passive Components',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Home Improvement',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Key Chain',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Laser Pointers',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Mini Projector',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Power Saver',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Surveillance',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Universal Adaptor',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Universal Remote',],
            [ 'l1' => 'Electronics', 'l2' => 'Gadgets', 'l3' => 'Other',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'DVD & CD Players',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'Hard Disk Players',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'Home Theater Systems',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'iPod & MP3 Accessories',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'iPod & MP3 Players',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'Speaker Systems',],
            [ 'l1' => 'Electronics', 'l2' => 'Home Theater & Media Players', 'l3' => 'Other',],
            [ 'l1' => 'Electronics', 'l2' => 'Satellite & Cable TV',],
            [ 'l1' => 'Electronics', 'l2' => 'Security Systems',],
            [ 'l1' => 'Electronics', 'l2' => 'Televisions',],
            [ 'l1' => 'Electronics', 'l2' => 'TV Accessories',],
            [ 'l1' => 'Electronics', 'l2' => 'Other Electronics',],
            [ 'l1' => 'Furniture & Storage',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Beddings',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Beddings', 'l4' => 'Bedsheet',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Beddings', 'l4' => 'Mattress',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Beddings', 'l4' => 'Pillows & Cases',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Beddings', 'l4' => 'Other',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Bedroom Sets',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Beds',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Dressing Table',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Wardrobes',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Bedroom Furniture', 'l3' => 'Other',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Dining Furniture',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Kids Furniture',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Kitchen Furniture',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Desks and Tables',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Filing Cabinets',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Bookshelves',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Chairs',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Conference Tables',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Cubicles and Partitions',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Office Furniture', 'l3' => 'Other',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'Bean Bags',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'Chairs and Stools',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'Cupboards and Cabinets',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'Sofa Beds',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'Sofas',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'Tables',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Sitting Room Furniture', 'l3' => 'TV Racks',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Hanging Storage',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Hooks & Rails',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Shoe Racks & Hangers',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Storage Bags',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Storage Baskets & Bins',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Storage Bottles & Jars',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Storage Boxes',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Storage Cabinets',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Storage Drawers',],
            [ 'l1' => 'Furniture & Storage', 'l2' => 'Storage & Organization', 'l3' => 'Styrofoam Box',],
            [ 'l1' => 'Health & Beauty',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Diet, Nutrition & Supplements',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Fragrances',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Glucose Monitors',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Insulin Injectors',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Lancets',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Monitoring Kits',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Socks & Insoles',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Test Strips',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Diabetes Care', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Face Mask',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'First Aid & Medical Supplies',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Hand Sanitizers',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Insect Repellents',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Massage & Relaxation',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Sexual Wellness',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Sleeping Aids',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Health Care', 'l3' => 'Other Healthcare',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Eye',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Eye', 'l4' => 'Eyeliner',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Eye', 'l4' => 'Eyeshadow',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Eye', 'l4' => 'Eylelashes',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Eye', 'l4' => 'Mascara',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Eye', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Face',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Face', 'l4' => 'Blush',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Face', 'l4' => 'Foundation',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Face', 'l4' => 'Powder',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Face', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Heena',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Lip',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Lip', 'l4' => 'Lip Balm',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Lip', 'l4' => 'Lip Gloss',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Lip', 'l4' => 'Lip Liner',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Lip', 'l4' => 'Lipstick',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Lip', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Makeup Bags',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Makeup Brushes',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Makeup Removers',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Makeup Sets & Kits',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Nail',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Nail', 'l4' => 'Manicure & Pedicure Kits',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Nail', 'l4' => 'Nail Art',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Nail', 'l4' => 'Nail Polish',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Nail', 'l4' => 'Nail Polish Remover',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Nail', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Makeup', 'l3' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Acne Treatment',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Cleansers',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Lightening Cream',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Masks',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Moisturizers',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Scrubs & Exfoliators',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Face Care', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Feminine Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Hair Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Nail Care, Manicure & Pedicure',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Oral Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal', 'l4' => 'Clippers & Trimmers',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal', 'l4' => 'Electric Shavers',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal', 'l4' => 'Razors & Razor Blades',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal', 'l4' => 'Scissors & Shears',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal', 'l4' => 'Waxing Supplies',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Shaving & Hair Removal', 'l4' => 'Other',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Skin Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Personal Care', 'l3' => 'Other Personal Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Weight Care',],
            [ 'l1' => 'Health & Beauty', 'l2' => 'Other Beauty',],
            [ 'l1' => 'Home & Garden',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Arts,Crafts & Sewing',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Arts,Crafts & Sewing', 'l3' => 'Sewing & Knitting',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Arts,Crafts & Sewing', 'l3' => 'Sewing & Knitting', 'l4' => 'Accessories',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Arts,Crafts & Sewing', 'l3' => 'Sewing & Knitting', 'l4' => 'Sewing Machines',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Arts,Crafts & Sewing', 'l3' => 'Sewing & Knitting', 'l4' => 'Yarn',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom', 'l3' => 'Basins & Vanities',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom', 'l3' => 'Mirrors',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom', 'l3' => 'Showers & Water Heaters',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom', 'l3' => 'Soap Dishes & Dispensers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom', 'l3' => 'Toilets',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Bathroom', 'l3' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Cooling & Air',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Cooling & Air', 'l3' => 'Airconditioners',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Cooling & Air', 'l3' => 'Fans',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Cooling & Air', 'l3' => 'Humidifiers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Cooling & Air', 'l3' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Curtains & Blinds',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Beverages',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Cake & Pastry',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Fruits',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Local Specialties',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Meat',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Seafood',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Vegetables',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Food and Beverages', 'l3' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Garden',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Garden', 'l3' => 'Gardening Supplies',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Garden', 'l3' => 'Plants and Trees',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Garden', 'l3' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Candles & Holders',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Carpet',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Clocks',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Cushions',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Flowers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Frames',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Pictures & Paintings',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Vases',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Wallpaper & Stickers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Home Decor', 'l3' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Cleaning',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Cleaning', 'l4' => 'Bins',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Cleaning', 'l4' => 'Brooms & Mops',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Cleaning', 'l4' => 'Cleaning Supplies',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Cleaning', 'l4' => 'Vacuum Cleaners & Accessories',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Cleaning', 'l4' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Clothes Hangers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Clothes Pins',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Clotheslines',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Detergent, Softener, Bleach',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Drying Racks',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Irons and Ironing Boards',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Laundry Baskets',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Washing Machines',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Laundry', 'l4' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Housekeeping', 'l3' => 'Pest Control',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Bakeware',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Coffee & Tea Making',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Cookware',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Cups & Glasses',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Cutlery & Utensils',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Dinnerware & Serving Dishes',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Fridge and Freezers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Blenders and Mixers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Cookers & Steamers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Grills & Fryers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Kettle and Water Heaters',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Kitchen Scale',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Oven - Convection',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Oven - Microwave',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Toasters & Waffle Irons',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Water Coolers, Filters & Dispensers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Kitchen Appliances', 'l4' => 'Other Kitchen Appliances',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Knives & Cutting',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Rice Cookers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Storage Containers',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Tableware & Linen',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Washing & Cleaning',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Kitchen & Dining', 'l3' => 'Other',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Chandeliers & Ceiling Fixtures',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Lamps & Shades',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Light Bulbs & Tubes',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Outdoor Lighting',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Portable Lighting',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Portable Lighting', 'l4' => 'Handheld Flashlight',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Portable Lighting', 'l4' => 'Headlamps',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Portable Lighting', 'l4' => 'Lantern Flashlight',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Portable Lighting', 'l4' => 'Portable Spotlights',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'String & Novelty Lighting',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Lights & Lighting', 'l3' => 'Lighting Parts & Accessories',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Towels',],
            [ 'l1' => 'Home & Garden', 'l2' => 'Other',],
            [ 'l1' => 'Industrial & Business',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Aggregates',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Bricks',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Cement',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Cladding',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Doors and Windows',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Electrical Supplies',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Elevators and Lifts',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Fire Systems',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Flooring',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Glass',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Paint and Coatings',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Roofing',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Steel',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Tiles / Marble / Granite',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Timber and Wood',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Building & Construction', 'l3' => 'Other',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Compressors & Pumps',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Engine, Generators & Motors',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Office',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Beverage Equipment',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Cooking & Warming Equipment',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Cookware & Kitchen Tools',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Refrigertation & Ice Machines',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Restaurant Furniture & Decor',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Tabletop',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Uniforms & Aprons',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Vending Equipment & Concessions',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Restaurant & Catering', 'l3' => 'Other',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Display Units & Racks',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Labeling & Tagging',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Mannequins',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Barcode Printers & Supplies',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Barcode Scanners',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Cash Drawer',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Counterfiet Detection & Bill Counter',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Pole Display',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'POS Software',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'POS System',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Programmable Keyboard',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Receipt Printers & Supplies',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Registers & Monitors',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Point of Sale', 'l4' => 'Other',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Retail Management', 'l3' => 'Other',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Tools',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Tools', 'l3' => 'Carpentry Tools & Equipment',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Tools', 'l3' => 'Hand Tools',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Tools', 'l3' => 'Power Tools',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Tools', 'l3' => 'Power Tools', 'l4' => 'Drills & Accessories',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Tools', 'l3' => 'Other Tools & Equipment',],
            [ 'l1' => 'Industrial & Business', 'l2' => 'Other',],
            [ 'l1' => 'Mobile Phones & Accessories',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Belt Holsters & Clips',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Car Accessories',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Cases, Protection & Skins',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Charger',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Data Cable',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Fashion and Decoration',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Headset - Bluetooth',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Headset - Wired',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Memory Card',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Power Bank',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Screen Protection',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Selfie Sticks & Stands',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Smart Watches',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Speakers',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Accessories', 'l3' => 'Other',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Mobile Phones',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Antenna',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Audio Jack',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Battery',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Button',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Camera Modules',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Charging Port',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Ear Speaker',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Flex Cable',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Frame',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Keypads',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'LCD Screen & Digitizer',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Loud Speaker',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Motherboard',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Phone Cover / Housing',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Tools',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Vibration Motor',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Parts', 'l3' => 'Other',],
            [ 'l1' => 'Mobile Phones & Accessories', 'l2' => 'Phone Numbers',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Bicycles',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Car & Van',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Car Accessories',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Battery',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Brake Systems',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Cover sets',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Engine Parts',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Exhaust',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Lights and Electricals',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Mirrors',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Safety and Security',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Suspension',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Wheels and Parts',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Motorcycle Accessories', 'l3' => 'Other',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Pickup, Lorry & Truck',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Rashu Pickup',],
            [ 'l1' => 'Motorcycle, Cars & Vehicles', 'l2' => 'Other',],
            [ 'l1' => 'Pets and Pet Supplies',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Birds',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Cages & Stands',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Aquarium & Tanks',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Cleaning & Maintenance',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Filters',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Fish & Aquatic Pets',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Food',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Lights & Bulbs',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Plant & Decor',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Pumps',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Fish & Aquarium', 'l3' => 'Other Aquarium Accessories',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Other Animals',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Pet Food',],
            [ 'l1' => 'Pets and Pet Supplies', 'l2' => 'Other Pet Supplies',],
            [ 'l1' => 'Sports, Fitness & Recreation',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Board Games',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Gym & Fitness Equipment',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Brass Instruments',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Drums & Percussion',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Guitars & String Instruments',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Karaoke Entertainment',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Piano, Keyboards & Organs',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Recording Equipment',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Stage Audio & Lighting',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Wind & Woodwind Instruments',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Musical Instruments', 'l3' => 'Other Musical Instruments & Accessories',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Skates, Skateboards & Scooters',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Skates, Skateboards & Scooters', 'l3' => 'Kick Scooters',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Skates, Skateboards & Scooters', 'l3' => 'Self Balancing Scooters',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Skates, Skateboards & Scooters', 'l3' => 'Skateboarding & Roller Skating',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Snooker, Pool & Billiard',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Sports Nutrition & Supplements',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Badminton',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Basketball',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football', 'l4' => 'Balls',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football', 'l4' => 'Jersey',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football', 'l4' => 'Protective Gear',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football', 'l4' => 'Shoes',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football', 'l4' => 'Vests',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Football', 'l4' => 'Other',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Volleyball',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Team Sports', 'l3' => 'Other Team Sports',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'Kites & Kitesurfing',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Boots & Gloves',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Buoyancy Compensators',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Dive Computers & Gauges',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Fins',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Masks, Snorkels & Sets',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Regulators',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Suits',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Suits', 'l5' => 'Hoods',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Suits', 'l5' => 'Rash Guards',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Suits', 'l5' => 'Shorts',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Suits', 'l5' => 'Wetsuits',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Suits', 'l5' => 'Other',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Tanks',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Accessories',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Accessories', 'l5' => 'Gear Bags',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Accessories', 'l5' => 'Knives',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Accessories', 'l5' => 'Lights',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Accessories', 'l5' => 'Mask Defoggers',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Accessories', 'l5' => 'Other Accessories',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'SCUBA & Snorkelling', 'l4' => 'Other',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'Surfing',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'Swimming',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'Wakeboarding & Waterskiing',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'Windsurfing',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Water Sports', 'l3' => 'Other',],
            [ 'l1' => 'Sports, Fitness & Recreation', 'l2' => 'Other Sporting Goods',],
            [ 'l1' => 'Stationery & Office Supplies',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Blank CDs and DVDs',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Filing and Binding Products',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Highlighters & Markers',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Notebooks & Writing Pads',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Office Electronics',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Office Electronics', 'l3' => 'Copiers',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Office Electronics', 'l3' => 'Fax Machines',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Office Electronics', 'l3' => 'Laminating',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Office Electronics', 'l3' => 'Shredders',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Office Electronics', 'l3' => 'Other',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Organizers',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Painting Supplies',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Paper',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Pens and Pencils',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Tapes, Adhesives & Fasteners',],
            [ 'l1' => 'Stationery & Office Supplies', 'l2' => 'Other',],
            [ 'l1' => 'Toys & Hobbies',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Educational Toys',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Outdoors',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'Drones',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'RC Airplanes',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'RC Boats',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'RC Cars & Trucks',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'RC Helicopters',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'RC Other',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Remote Control Toys', 'l3' => 'Parts & Accessories',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Soft and Stuffed Toys',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Toy Vehicles & Diecasts',],
            [ 'l1' => 'Toys & Hobbies', 'l2' => 'Other',],
            [ 'l1' => 'Video & Computer Gaming',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Accessories',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Accessories', 'l3' => 'Battery and Charger',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Accessories', 'l3' => 'Data and Power Cables',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Accessories', 'l3' => 'Game Controllers',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Accessories', 'l3' => 'Memory',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Accessories', 'l3' => 'Other',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Consoles',],
            [ 'l1' => 'Video & Computer Gaming', 'l2' => 'Games',],
            [ 'l1' => 'Other Stuff',],
            [ 'l1' => 'Housing & Real Estate',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Apartments & Houses for Rent',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Room for Rent',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Guest Houses & Short Stay Accomodation',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Kudhin Baithibbaadhinun',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Land For Sale & Lease',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Office & Commercial Space',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'Roommates Wanted',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'International',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'International', 'l3' => 'Apartments & Houses for Rent',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'International', 'l3' => 'Guest Houses & Short Stay Accomodation',],
            [ 'l1' => 'Housing & Real Estate', 'l2' => 'International', 'l3' => 'Kudhin Baithibbaadhinun',],
            [ 'l1' => 'Jobs',],
            [ 'l1' => 'Services',],
            [ 'l1' => 'Services', 'l2' => 'Architectural & Home Design',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Aerobics and Zumba Classes',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Beauty Services',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Gym and Fitness Studios',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Martial Arts Classes',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Personal Trainer',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Racket Stringing',],
            [ 'l1' => 'Services', 'l2' => 'Beauty, Sports and Wellness', 'l3' => 'Sports Coach',],
            [ 'l1' => 'Services', 'l2' => 'Business Services',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Accounting & Auditing',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Advertising & Marketing',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Business Consulting',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Cargo Handling & Logistics',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Computer & Telecom Networking',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Courier and Delivery',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Foreign Labor Recruitment & Services',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Legal',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Printing',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Secretarial Services',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Security Services',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Signboard Making',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Software Development',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Transport',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Web & Graphics Design',],
            [ 'l1' => 'Services', 'l2' => 'Business Services', 'l3' => 'Web Hosting',],
            [ 'l1' => 'Services', 'l2' => 'Domestic Services',],
            [ 'l1' => 'Services', 'l2' => 'Domestic Services', 'l3' => 'Babysitting and Child Care',],
            [ 'l1' => 'Services', 'l2' => 'Domestic Services', 'l3' => 'Cooking',],
            [ 'l1' => 'Services', 'l2' => 'Domestic Services', 'l3' => 'Laundry',],
            [ 'l1' => 'Services', 'l2' => 'Domestic Services', 'l3' => 'Maid',],
            [ 'l1' => 'Services', 'l2' => 'Event Services',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Cake',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Catering & Takeaway',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Corporate Event Planners',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Florists',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Function Venues',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Live Bands and Musicians',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Party Planners',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Party Supplies & Decoration',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Sound and Lighting',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Video & Photography',],
            [ 'l1' => 'Services', 'l2' => 'Event Services', 'l3' => 'Wedding Planners',],
            [ 'l1' => 'Services', 'l2' => 'Food Services',],
            [ 'l1' => 'Services', 'l2' => 'Healthcare Services',],
            [ 'l1' => 'Services', 'l2' => 'Industrial',],
            [ 'l1' => 'Services', 'l2' => 'Industrial', 'l3' => 'Boat Building & Related Services',],
            [ 'l1' => 'Services', 'l2' => 'Industrial', 'l3' => 'Welding & Engineering',],
            [ 'l1' => 'Services', 'l2' => 'Rental Services',],
            [ 'l1' => 'Services', 'l2' => 'Rental Services', 'l3' => 'Catering Utensils & Supplies',],
            [ 'l1' => 'Services', 'l2' => 'Rental Services', 'l3' => 'Chairs & Tables',],
            [ 'l1' => 'Services', 'l2' => 'Rental Services', 'l3' => 'Dhoani and Marine Vessels',],
            [ 'l1' => 'Services', 'l2' => 'Rental Services', 'l3' => 'Pickup & Heavy Vehicles',],
            [ 'l1' => 'Services', 'l2' => 'Rental Services', 'l3' => 'Tools & Equipment',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Aircon Servicing & Repair',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Building & Construction',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Camera Repair',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Carpentry',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Computer Repairs',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Dhonna Machine Maraamathukurun',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Electrical & Wiring',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Fen Motor Maraamathukurun',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Housekeeping & Cleaning',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Movers',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Pest Control',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Phone Servicing & Unlocking',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Plumbing',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Television Repair',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Vehicle Garage',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'Video Game Repair & Services',],
            [ 'l1' => 'Services', 'l2' => 'Repairs, Maintenance & Household Work', 'l3' => 'General / Other',],
            [ 'l1' => 'Services', 'l2' => 'Tailoring',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Island Overview & Information',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Picnic, Fishing Trips & Other Activities',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Restaurants & Cafes',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Transport & Vehicle Rental',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Transport & Vehicle Rental', 'l4' => 'Bicycle Rental',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Transport & Vehicle Rental', 'l4' => 'Ferry & Naalu Boat',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Transport & Vehicle Rental', 'l4' => 'Motorcycle Rental',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Transport & Vehicle Rental', 'l4' => 'Speedboat & Dhoani Rental',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Transport & Vehicle Rental', 'l4' => 'Taxi & Car Rental',],
            [ 'l1' => 'Services', 'l2' => 'Travel & Recreation', 'l3' => 'Travel Packages',],
            [ 'l1' => 'Services', 'l2' => 'Tuition & Personal Development',],
            [ 'l1' => 'Services', 'l2' => 'Tuition & Personal Development', 'l3' => 'Cooking & Baking Classes',],
            [ 'l1' => 'Services', 'l2' => 'Tuition & Personal Development', 'l3' => 'Driving Classes',],
            [ 'l1' => 'Services', 'l2' => 'Tuition & Personal Development', 'l3' => 'Training',],
            [ 'l1' => 'Services', 'l2' => 'Tuition & Personal Development', 'l3' => 'Tuition',],
            [ 'l1' => 'Services', 'l2' => 'Other Services',],
            [ 'l1' => 'Services', 'l2' => 'Other Services', 'l3' => 'Audio & Video Recording',],
            [ 'l1' => 'Services', 'l2' => 'Other Services', 'l3' => 'Buying from Abroad',],
            [ 'l1' => 'Services', 'l2' => 'Other Services', 'l3' => 'Vehicle Registration & Roadworthiness',],
            [ 'l1' => 'Services', 'l2' => 'Other Services', 'l3' => 'Other Services',],
            [ 'l1' => 'Wanted',],
            [ 'l1' => 'Wanted', 'l2' => 'Books and Magazines',],
            [ 'l1' => 'Wanted', 'l2' => 'Clothing and Accessories',],
            [ 'l1' => 'Wanted', 'l2' => 'Computer Laptop and Accessories',],
            [ 'l1' => 'Wanted', 'l2' => 'Electronics',],
            [ 'l1' => 'Wanted', 'l2' => 'Mobile Phones and Accessories',],
            [ 'l1' => 'Wanted', 'l2' => 'Motorcycles- Cars and Accessories',],
            [ 'l1' => 'Wanted', 'l2' => 'Real Estate - Office Space and Commercial',],
            [ 'l1' => 'Wanted', 'l2' => 'Real Estate - Rooms and Apartment',],
            [ 'l1' => 'Wanted', 'l2' => 'Services',],
            [ 'l1' => 'Wanted', 'l2' => 'Sporting Goods',],
            [ 'l1' => 'Wanted', 'l2' => 'Toys Kids and Hobbies',],
            [ 'l1' => 'Wanted', 'l2' => 'Other Stuff',],
            [ 'l1' => 'Business Opportunities',],
            [ 'l1' => 'Business Opportunities', 'l2' => 'Business for Sale',],
            [ 'l1' => 'Business Opportunities', 'l2' => 'Websites for Sale',],
            [ 'l1' => 'Business Opportunities', 'l2' => 'Other',],
            [ 'l1' => 'Announcements & Events',],
            [ 'l1' => 'Announcements & Events', 'l2' => 'Announcements',],
            [ 'l1' => 'Announcements & Events', 'l2' => 'Lost and Found',],
            [ 'l1' => 'Announcements & Events', 'l2' => 'Promotions',],
            [ 'l1' => 'Announcements & Events', 'l2' => 'Trade Exhibitions & Fairs',],
            [ 'l1' => 'Announcements & Events', 'l2' => 'Other',],
            [ 'l1' => 'Free Stuff',],
        ];
    }

}
