<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CategorySeederV2 extends CategorySeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = $this->getCategories();

        $category = new Category();

        //first add level 1 categories
        foreach ($categories as $data) {
            if (count($data) == 1) {
                $category->create([
                    'name' => $data[0],
                    'level' => 1,
                    'parent_id' => null,
                    'category_name' => $data[0],
                ]);
            }
        }

        //then add level 2 categories
        foreach ($categories as $data) {
            if (count($data) == 2) {

                $level1 = $category->where('name', $data[0])->first();

                $category->create([
                    'name' => $data[1],
                    'level' => 2,
                    'parent_id' => $level1->id,
                    'category' => $level1->id,
                    'category_name' => $level1->name,
                    'sub_category_name' => $data[1],
                ]);
            }
        }

        //then add level 3 categories
        foreach ($categories as $data) {
            if (count($data) == 3) {

                $level1 = $category->where('name', $data[0])->first();
                $level2 = $category->where('name', $data[1])->first();

                $category->create([
                    'name' => $data[2],
                    'level' => 3,
                    'parent_id' => $level2->id,
                    'category' => $level1->id,
                    'sub_category' => $level2->id,
                    'category_name' => $level1->name,
                    'sub_category_name' => $level2->name,
                    'third_level_category_name' => $data[2],
                ]);
            }
        }

        //then add level 4 categories
        foreach ($categories as $data) {
            if (count($data) == 4) {

                $level1 = $category->where('name', $data[0])->first();
                $level2 = $category->where('name', $data[1])->first();
                $level3 = $category->where('name', $data[2])->first();

                try {
                    $category->create([
                        'name' => $data[3],
                        'level' => 4,
                        'parent_id' => $level3->id,
                        'category' => $level1->id,
                        'sub_category' => $level2->id,
                        'third_level_category' => $level3->id,
                        'category_name' => $level1->name,
                        'sub_category_name' => $level2->name,
                        'third_level_category_name' => $level3->name,
                        'fourth_level_category_name' => $data[3],
                    ]);
                } catch (\Exception $e) {
                    dd($data);
                }

            }
        }

        //then add level 5 categories
        foreach ($categories as $data) {
            if (count($data) == 5) {

                $level1 = $category->where('name', $data[0])->first();
                $level2 = $category->where('name', $data[1])->first();
                $level3 = $category->where('name', $data[2])->first();
                $level4 = $category->where('name', $data[3])->first();

                $category->create([
                    'name' => $data[4],
                    'level' => 5,
                    'parent_id' => $level4->id,
                    'category' => $level1->id,
                    'sub_category' => $level2->id,
                    'third_level_category' => $level3->id,
                    'fourth_level_category' => $level4->id,
                    'category_name' => $level1->name,
                    'sub_category_name' => $level2->name,
                    'third_level_category_name' => $level3->name,
                    'fourth_level_category_name' => $level4->name,
                    'fifth_level_category_name' => $data[4],
                ]);
            }

        }
       
        $this->fillRemainingFields();
        


        // foreach ($categories as $data) {

        //     if (count($data) == 5) {
        //         $name = $data[4];
        //         $parentId = $data[3];
        //     }
            
        //     if (count($data) == 4) {
        //         $name = $data[3];
        //         $parentId = $data[2];
        //     }
            
        //     if (count($data) == 3) {
        //         $name = $data[2];
        //         $parentId = $data[1];
        //     }
            
        //     if (count($data) == 2) {
        //         $name = $data[1];
        //         $parentId = $data[0];
        //     }
            
        //     if (count($data) == 1) {
        //         $name = $data[0];
        //         $parentId = null;
        //     }
            
        //     $category->create([                
        //         'name' => $name,
        //         // 'slug' =>
        //         // 'mtime' =>
        //         // 'images' =>
        //         'parent_id' => $parentId,
        //         'level' => count($data),
        //         // 'category' =>
        //         // 'category_name' =>
        //         // 'category_slug' =>
        //         // 'sub_category' =>
        //         // 'sub_category_name' =>
        //         // 'sub_category_slug' =>
        //         // 'third_level_category' =>
        //         // 'third_level_category_name' =>
        //         // 'third_level_category_slug' =>
        //         // 'fourth_level_category' =>
        //         // 'fourth_level_category_name' =>
        //         // 'fourth_level_category_slug' =>
        //         // 'fifth_level_category' =>
        //         // 'fifth_level_category_name' =>
        //         // 'fifth_level_category_slug' =>
        //         // 'path' =>
        //         // 'is_selectable' =>
        //     ]);
        //     // $category->create($data);
            
        // }
    }

    public function getCategories()
    {
        return [
            [ 0 => 'Antiques, Collectibles & Gifts',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Antiques',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Coins and Paper Money',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Gifts',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Sovenirs',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Sports Memorabilia',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Stamps',],
            [ 0 => 'Antiques, Collectibles & Gifts', 1 => 'Other Collectibles',],
            [ 0 => 'Baby, Pregnancy & Maternity',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Baby Carriers & Backpacks',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Baby Shoes',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Baby Toys',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Bathing & Grooming',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Clothing & Accessories',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Diapering',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'Bibs',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'Bottles',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'Breast Pumps',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'High Chairs',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'Plates, Bowels & Cups',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'Sterilisers & Food Warmers',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Feeding', 2 => 'Other',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Furniture & Bedding',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Health & Baby Care',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Maternity',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Nursery Decor',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Pregnancy',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Strollers & Walkers',],
            [ 0 => 'Baby, Pregnancy & Maternity', 1 => 'Other Baby Products',],
            [ 0 => 'Books & Magazines',],
            [ 0 => 'Books & Magazines', 1 => 'Children & Babies',],
            [ 0 => 'Books & Magazines', 1 => 'Children & Babies', 2 => 'Activity & Colouring',],
            [ 0 => 'Books & Magazines', 1 => 'Children & Babies', 2 => 'Educational',],
            [ 0 => 'Books & Magazines', 1 => 'Children & Babies', 2 => 'Other',],
            [ 0 => 'Books & Magazines', 1 => 'Comics',],
            [ 0 => 'Books & Magazines', 1 => 'Fiction',],
            [ 0 => 'Books & Magazines', 1 => 'Magazines',],
            [ 0 => 'Books & Magazines', 1 => 'Non-Fiction',],
            [ 0 => 'Books & Magazines', 1 => 'Textbooks',],
            [ 0 => 'Books & Magazines', 1 => 'Young Adult Fiction',],
            [ 0 => 'Books & Magazines', 1 => 'Other',],
            [ 0 => 'Clothing & Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Athletic & Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Hoodies & Sweater',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Jackets & Coats',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'School Uniforms',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Shirts & T-Shirts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Shorts & Beachwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Sleepwear & Lounge',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Socks',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Underwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Clothing', 4 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'Athletic & Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'Flip Flops',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'Loafers & Slip-Ons',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'Sandals',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'School Shoes',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'Sneakers',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Footwear', 4 => 'Other Footwear & Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Hats & Caps',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Boys', 3 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Athletic & Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Dresses & Skirts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Hoodies & Sweater',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Jackets & Coats',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Jeans & Pants',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Leggings',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'School Uniforms',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Shirts, T-Shirts & Tops',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Shorts & Beachwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Sleepwear & Lounge',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Socks',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Underwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Clothing', 4 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Athletic & Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Flats',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Flip Flops',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Loafers & Slip-Ons',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Sandals',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'School Shoes',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Sneakers',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Footwear', 4 => 'Other Footwear & Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Hair Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Hats & Caps',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Jewelry',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Girls', 3 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Costumes',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'School Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Sunglasses',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Watches',],
            [ 0 => 'Clothing & Accessories', 1 => 'Men',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Athletic & Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Flip Flops',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Formal Shoes & Boots',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Loafers & Slip-Ons',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Sandals',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Sneakers',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Other Footwear & Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Belts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Bracelets & Wristbands',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Cufflinks',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Handkerchiefs',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Hats & Caps',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Necklaces, Rings & Earrings',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Ties',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Wallets',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Accessories', 3 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Athletic and Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Beachwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Hoodies & Sweater',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Jeans',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Pants',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Shirts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Shorts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Sleep & Lounge',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Socks',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'T-Shirts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Underwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Men Clothing', 3 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Women',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Athletic & Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Flats',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Flip Flops',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Formal Shoes & Boots',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Heels',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Loafers & Slip-Ons',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Sandals',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Sneakers',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Footwear', 3 => 'Other Footwear & Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Belts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Bracelets',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Burugaa Dathi and Pins',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Earrings',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Fashu Foo',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Hair Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Handbag & Purse',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Hats & Caps',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Necklaces',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Rings',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Accessories', 3 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Athletic and Sports',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Beach and Swimwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Bras',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Buruga & Shawl',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Dresses',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Hoodies & Sweater',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Jeans',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Kurutha and Tops',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Leggings',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Lingerie & Shapewear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Panties',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Pants',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Shorts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Skirts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Sleepwear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Socks & Tights',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'T-Shirts',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Women Clothing', 3 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Sunglasses',],
            [ 0 => 'Clothing & Accessories', 1 => 'Travel & Bags',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Backpacks',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Briefcases',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Gym Bags',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Luggage & Travel Bags',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Messenger Bags',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'School Bags',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Travel Accessories',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Umbrellas & Rain Wear',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Waist Packs',],
            [ 0 => 'Clothing & Accessories', 1 => 'Kids', 2 => 'Other',],
            [ 0 => 'Clothing & Accessories', 1 => 'Watches',],
            [ 0 => 'Clothing & Accessories', 1 => 'Other Clothing & Accessories',],
            [ 0 => 'Computer, Tablets & Networking',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Card Readers & USB Hubs',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage', 3 => 'DVD & CD Drives',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage', 3 => 'Hard Drives - External',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage', 3 => 'Hard Drives - Laptop',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage', 3 => 'Hard Drives- Internal',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage', 3 => 'Pen Drive',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Drives & Storage', 3 => 'Other',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Graphics Cards',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Keyboards, Mouse & Input Devices',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Keyboards, Mouse & Input Devices', 3 => 'Keyboards',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Keyboards, Mouse & Input Devices', 3 => 'Mouse',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Keyboards, Mouse & Input Devices', 3 => 'Mouse & Keyboard Bundles',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Keyboards, Mouse & Input Devices', 3 => 'Other',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Memory',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Memory', 3 => 'Laptop Memory',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Memory', 3 => 'PC Memory',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Monitors',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Motherboard',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Power Supplies',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Processor',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Projectors',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Sound Card',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Speakers & Headphones',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Webcams',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Accessories & Parts', 2 => 'Other Accessories',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Desktop',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories', 2 => 'Battery',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories', 2 => 'Carrying Cases and Bags',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories', 2 => 'Charger',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories', 2 => 'Cooling Pad',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories', 2 => 'Power Adapter',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Laptop Accessories', 2 => 'Other',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Modems',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Routers & Switches',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Servers',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Wireless Networking',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Wireless Networking', 3 => 'Accessories and Parts',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Wireless Networking', 3 => 'Bluetooth',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Wireless Networking', 3 => 'Mobile Modem',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Wireless Networking', 3 => 'Routers and Access Points',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Wireless Networking', 3 => 'USB Dongles',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Networking', 2 => 'Other',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Printer Supplies & Accessories',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Printers & Scanners',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Software',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Tablet Accessories',],
            [ 0 => 'Computer, Tablets & Networking', 1 => 'Tablets',],
            [ 0 => 'Dhoani, Boats & Fishing',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC', 2 => 'Dhoani',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC', 2 => 'Dinghies & Bokkura',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC', 2 => 'Jet Ski / PWC',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC', 2 => 'Passenger & Safari Boats',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC', 2 => 'Speedboat',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Dhoani, Boats & PWC', 2 => 'Other Marine Vessels',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Fish Finders',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Fishing Line',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Lures and Hooks',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Reels',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Rods',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Rods and Reels',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Vadhu Foshi',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Fishing', 2 => 'Other',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Marine Engines & Parts',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Marine Engines & Parts', 2 => 'Engines',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Marine Engines & Parts', 2 => 'Parts & Accessories',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Anchors',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Buoys & Fenders',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Lifejackets',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Navigation Equipment',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Propellers',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Safety',],
            [ 0 => 'Dhoani, Boats & Fishing', 1 => 'Parts & Accessories', 2 => 'Other',],
            [ 0 => 'Electronics',],
            [ 0 => 'Electronics', 1 => 'Batteries & Chargers',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Digital Camera',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Binoculars & Telescopes',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camcorders',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Drone',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Battery and Charger',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Cases and Bags',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Flashes',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Lenses',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Photo Studio Supplies',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Tripods & Monopods',],
            [ 0 => 'Electronics', 1 => 'Camera, Photo & Video', 2 => 'Camera Accessories', 3 => 'Other Accessories',],
            [ 0 => 'Electronics', 1 => 'Electronic Components & Supplies',],
            [ 0 => 'Electronics', 1 => 'Electronic Components & Supplies', 2 => 'Active Components',],
            [ 0 => 'Electronics', 1 => 'Electronic Components & Supplies', 2 => 'Passive Components',],
            [ 0 => 'Electronics', 1 => 'Gadgets',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Home Improvement',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Key Chain',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Laser Pointers',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Mini Projector',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Power Saver',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Surveillance',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Universal Adaptor',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Universal Remote',],
            [ 0 => 'Electronics', 1 => 'Gadgets', 2 => 'Other',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'DVD & CD Players',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'Hard Disk Players',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'Home Theater Systems',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'iPod & MP3 Accessories',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'iPod & MP3 Players',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'Speaker Systems',],
            [ 0 => 'Electronics', 1 => 'Home Theater & Media Players', 2 => 'Other',],
            [ 0 => 'Electronics', 1 => 'Satellite & Cable TV',],
            [ 0 => 'Electronics', 1 => 'Security Systems',],
            [ 0 => 'Electronics', 1 => 'Televisions',],
            [ 0 => 'Electronics', 1 => 'TV Accessories',],
            [ 0 => 'Electronics', 1 => 'Other Electronics',],
            [ 0 => 'Furniture & Storage',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Beddings',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Beddings', 3 => 'Bedsheet',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Beddings', 3 => 'Mattress',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Beddings', 3 => 'Pillows & Cases',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Beddings', 3 => 'Other',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Bedroom Sets',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Beds',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Dressing Table',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Wardrobes',],
            [ 0 => 'Furniture & Storage', 1 => 'Bedroom Furniture', 2 => 'Other',],
            [ 0 => 'Furniture & Storage', 1 => 'Dining Furniture',],
            [ 0 => 'Furniture & Storage', 1 => 'Kids Furniture',],
            [ 0 => 'Furniture & Storage', 1 => 'Kitchen Furniture',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Desks and Tables',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Filing Cabinets',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Bookshelves',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Chairs',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Conference Tables',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Cubicles and Partitions',],
            [ 0 => 'Furniture & Storage', 1 => 'Office Furniture', 2 => 'Other',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'Bean Bags',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'Chairs and Stools',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'Cupboards and Cabinets',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'Sofa Beds',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'Sofas',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'Tables',],
            [ 0 => 'Furniture & Storage', 1 => 'Sitting Room Furniture', 2 => 'TV Racks',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Hanging Storage',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Hooks & Rails',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Shoe Racks & Hangers',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Storage Bags',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Storage Baskets & Bins',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Storage Bottles & Jars',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Storage Boxes',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Storage Cabinets',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Storage Drawers',],
            [ 0 => 'Furniture & Storage', 1 => 'Storage & Organization', 2 => 'Styrofoam Box',],
            [ 0 => 'Health & Beauty',],
            [ 0 => 'Health & Beauty', 1 => 'Diet, Nutrition & Supplements',],
            [ 0 => 'Health & Beauty', 1 => 'Fragrances',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Glucose Monitors',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Insulin Injectors',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Lancets',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Monitoring Kits',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Socks & Insoles',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Test Strips',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Diabetes Care', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Face Mask',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'First Aid & Medical Supplies',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Hand Sanitizers',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Insect Repellents',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Massage & Relaxation',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Sexual Wellness',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Sleeping Aids',],
            [ 0 => 'Health & Beauty', 1 => 'Health Care', 2 => 'Other Healthcare',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Eye',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Eye', 3 => 'Eyeliner',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Eye', 3 => 'Eyeshadow',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Eye', 3 => 'Eylelashes',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Eye', 3 => 'Mascara',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Eye', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Face',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Face', 3 => 'Blush',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Face', 3 => 'Foundation',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Face', 3 => 'Powder',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Face', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Heena',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Lip',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Lip', 3 => 'Lip Balm',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Lip', 3 => 'Lip Gloss',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Lip', 3 => 'Lip Liner',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Lip', 3 => 'Lipstick',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Lip', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Makeup Bags',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Makeup Brushes',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Makeup Removers',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Makeup Sets & Kits',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Nail',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Nail', 3 => 'Manicure & Pedicure Kits',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Nail', 3 => 'Nail Art',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Nail', 3 => 'Nail Polish',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Nail', 3 => 'Nail Polish Remover',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Nail', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Makeup', 2 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Acne Treatment',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Cleansers',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Lightening Cream',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Masks',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Moisturizers',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Scrubs & Exfoliators',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Face Care', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Feminine Care',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Hair Care',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Nail Care, Manicure & Pedicure',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Oral Care',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal', 3 => 'Clippers & Trimmers',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal', 3 => 'Electric Shavers',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal', 3 => 'Razors & Razor Blades',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal', 3 => 'Scissors & Shears',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal', 3 => 'Waxing Supplies',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Shaving & Hair Removal', 3 => 'Other',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Skin Care',],
            [ 0 => 'Health & Beauty', 1 => 'Personal Care', 2 => 'Other Personal Care',],
            [ 0 => 'Health & Beauty', 1 => 'Weight Care',],
            [ 0 => 'Health & Beauty', 1 => 'Other Beauty',],
            [ 0 => 'Home & Garden',],
            [ 0 => 'Home & Garden', 1 => 'Arts,Crafts & Sewing',],
            [ 0 => 'Home & Garden', 1 => 'Arts,Crafts & Sewing', 2 => 'Sewing & Knitting',],
            [ 0 => 'Home & Garden', 1 => 'Arts,Crafts & Sewing', 2 => 'Sewing & Knitting', 3 => 'Accessories',],
            [ 0 => 'Home & Garden', 1 => 'Arts,Crafts & Sewing', 2 => 'Sewing & Knitting', 3 => 'Sewing Machines',],
            [ 0 => 'Home & Garden', 1 => 'Arts,Crafts & Sewing', 2 => 'Sewing & Knitting', 3 => 'Yarn',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom', 2 => 'Basins & Vanities',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom', 2 => 'Mirrors',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom', 2 => 'Showers & Water Heaters',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom', 2 => 'Soap Dishes & Dispensers',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom', 2 => 'Toilets',],
            [ 0 => 'Home & Garden', 1 => 'Bathroom', 2 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Cooling & Air',],
            [ 0 => 'Home & Garden', 1 => 'Cooling & Air', 2 => 'Airconditioners',],
            [ 0 => 'Home & Garden', 1 => 'Cooling & Air', 2 => 'Fans',],
            [ 0 => 'Home & Garden', 1 => 'Cooling & Air', 2 => 'Humidifiers',],
            [ 0 => 'Home & Garden', 1 => 'Cooling & Air', 2 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Curtains & Blinds',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Beverages',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Cake & Pastry',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Fruits',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Local Specialties',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Meat',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Seafood',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Vegetables',],
            [ 0 => 'Home & Garden', 1 => 'Food and Beverages', 2 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Garden',],
            [ 0 => 'Home & Garden', 1 => 'Garden', 2 => 'Gardening Supplies',],
            [ 0 => 'Home & Garden', 1 => 'Garden', 2 => 'Plants and Trees',],
            [ 0 => 'Home & Garden', 1 => 'Garden', 2 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Candles & Holders',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Carpet',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Clocks',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Cushions',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Flowers',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Frames',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Pictures & Paintings',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Vases',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Wallpaper & Stickers',],
            [ 0 => 'Home & Garden', 1 => 'Home Decor', 2 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Cleaning',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Cleaning', 3 => 'Bins',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Cleaning', 3 => 'Brooms & Mops',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Cleaning', 3 => 'Cleaning Supplies',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Cleaning', 3 => 'Vacuum Cleaners & Accessories',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Cleaning', 3 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Clothes Hangers',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Clothes Pins',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Clotheslines',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Detergent, Softener, Bleach',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Drying Racks',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Irons and Ironing Boards',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Laundry Baskets',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Washing Machines',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Laundry', 3 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Housekeeping', 2 => 'Pest Control',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Bakeware',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Coffee & Tea Making',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Cookware',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Cups & Glasses',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Cutlery & Utensils',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Dinnerware & Serving Dishes',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Fridge and Freezers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Blenders and Mixers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Cookers & Steamers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Grills & Fryers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Kettle and Water Heaters',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Kitchen Scale',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Oven - Convection',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Oven - Microwave',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Toasters & Waffle Irons',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Water Coolers, Filters & Dispensers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Kitchen Appliances', 3 => 'Other Kitchen Appliances',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Knives & Cutting',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Rice Cookers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Storage Containers',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Tableware & Linen',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Washing & Cleaning',],
            [ 0 => 'Home & Garden', 1 => 'Kitchen & Dining', 2 => 'Other',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Chandeliers & Ceiling Fixtures',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Lamps & Shades',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Light Bulbs & Tubes',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Outdoor Lighting',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Portable Lighting',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Portable Lighting', 3 => 'Handheld Flashlight',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Portable Lighting', 3 => 'Headlamps',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Portable Lighting', 3 => 'Lantern Flashlight',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Portable Lighting', 3 => 'Portable Spotlights',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'String & Novelty Lighting',],
            [ 0 => 'Home & Garden', 1 => 'Lights & Lighting', 2 => 'Lighting Parts & Accessories',],
            [ 0 => 'Home & Garden', 1 => 'Towels',],
            [ 0 => 'Home & Garden', 1 => 'Other',],
            [ 0 => 'Industrial & Business',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Aggregates',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Bricks',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Cement',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Cladding',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Doors and Windows',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Electrical Supplies',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Elevators and Lifts',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Fire Systems',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Flooring',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Glass',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Paint and Coatings',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Roofing',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Steel',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Tiles / Marble / Granite',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Timber and Wood',],
            [ 0 => 'Industrial & Business', 1 => 'Building & Construction', 2 => 'Other',],
            [ 0 => 'Industrial & Business', 1 => 'Compressors & Pumps',],
            [ 0 => 'Industrial & Business', 1 => 'Engine, Generators & Motors',],
            [ 0 => 'Industrial & Business', 1 => 'Office',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Beverage Equipment',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Cooking & Warming Equipment',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Cookware & Kitchen Tools',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Refrigertation & Ice Machines',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Restaurant Furniture & Decor',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Tabletop',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Uniforms & Aprons',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Vending Equipment & Concessions',],
            [ 0 => 'Industrial & Business', 1 => 'Restaurant & Catering', 2 => 'Other',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Display Units & Racks',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Labeling & Tagging',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Mannequins',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Barcode Printers & Supplies',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Barcode Scanners',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Cash Drawer',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Counterfiet Detection & Bill Counter',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Pole Display',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'POS Software',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'POS System',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Programmable Keyboard',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Receipt Printers & Supplies',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Registers & Monitors',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Point of Sale', 3 => 'Other',],
            [ 0 => 'Industrial & Business', 1 => 'Retail Management', 2 => 'Other',],
            [ 0 => 'Industrial & Business', 1 => 'Tools',],
            [ 0 => 'Industrial & Business', 1 => 'Tools', 2 => 'Carpentry Tools & Equipment',],
            [ 0 => 'Industrial & Business', 1 => 'Tools', 2 => 'Hand Tools',],
            [ 0 => 'Industrial & Business', 1 => 'Tools', 2 => 'Power Tools',],
            [ 0 => 'Industrial & Business', 1 => 'Tools', 2 => 'Power Tools', 3 => 'Drills & Accessories',],
            [ 0 => 'Industrial & Business', 1 => 'Tools', 2 => 'Other Tools & Equipment',],
            [ 0 => 'Industrial & Business', 1 => 'Other',],
            [ 0 => 'Mobile Phones & Accessories',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Belt Holsters & Clips',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Car Accessories',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Cases, Protection & Skins',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Charger',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Data Cable',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Fashion and Decoration',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Headset - Bluetooth',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Headset - Wired',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Memory Card',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Power Bank',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Screen Protection',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Selfie Sticks & Stands',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Smart Watches',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Speakers',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Accessories', 2 => 'Other',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Mobile Phones',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Antenna',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Audio Jack',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Battery',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Button',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Camera Modules',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Charging Port',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Ear Speaker',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Flex Cable',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Frame',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Keypads',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'LCD Screen & Digitizer',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Loud Speaker',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Motherboard',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Phone Cover / Housing',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Tools',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Vibration Motor',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Parts', 2 => 'Other',],
            [ 0 => 'Mobile Phones & Accessories', 1 => 'Phone Numbers',],
            [ 0 => 'Motorcycle, Cars & Vehicles',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Bicycles',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Car & Van',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Car Accessories',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Battery',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Brake Systems',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Cover sets',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Engine Parts',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Exhaust',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Lights and Electricals',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Mirrors',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Safety and Security',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Suspension',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Wheels and Parts',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Motorcycle Accessories', 2 => 'Other',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Pickup, Lorry & Truck',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Rashu Pickup',],
            [ 0 => 'Motorcycle, Cars & Vehicles', 1 => 'Other',],
            [ 0 => 'Pets and Pet Supplies',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Birds',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Cages & Stands',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Aquarium & Tanks',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Cleaning & Maintenance',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Filters',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Fish & Aquatic Pets',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Food',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Lights & Bulbs',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Plant & Decor',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Pumps',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Fish & Aquarium', 2 => 'Other Aquarium Accessories',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Other Animals',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Pet Food',],
            [ 0 => 'Pets and Pet Supplies', 1 => 'Other Pet Supplies',],
            [ 0 => 'Sports, Fitness & Recreation',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Board Games',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Gym & Fitness Equipment',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Brass Instruments',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Drums & Percussion',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Guitars & String Instruments',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Karaoke Entertainment',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Piano, Keyboards & Organs',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Recording Equipment',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Stage Audio & Lighting',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Wind & Woodwind Instruments',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Musical Instruments', 2 => 'Other Musical Instruments & Accessories',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Skates, Skateboards & Scooters',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Skates, Skateboards & Scooters', 2 => 'Kick Scooters',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Skates, Skateboards & Scooters', 2 => 'Self Balancing Scooters',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Skates, Skateboards & Scooters', 2 => 'Skateboarding & Roller Skating',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Snooker, Pool & Billiard',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Sports Nutrition & Supplements',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Badminton',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Basketball',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football', 3 => 'Balls',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football', 3 => 'Jersey',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football', 3 => 'Protective Gear',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football', 3 => 'Shoes',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football', 3 => 'Vests',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Football', 3 => 'Other',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Volleyball',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Team Sports', 2 => 'Other Team Sports',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'Kites & Kitesurfing',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Boots & Gloves',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Buoyancy Compensators',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Dive Computers & Gauges',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Fins',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Masks, Snorkels & Sets',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Regulators',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Suits',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Suits', 4 => 'Hoods',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Suits', 4 => 'Rash Guards',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Suits', 4 => 'Shorts',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Suits', 4 => 'Wetsuits',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Suits', 4 => 'Other',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Tanks',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Accessories',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Accessories', 4 => 'Gear Bags',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Accessories', 4 => 'Knives',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Accessories', 4 => 'Lights',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Accessories', 4 => 'Mask Defoggers',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Accessories', 4 => 'Other Accessories',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'SCUBA & Snorkelling', 3 => 'Other',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'Surfing',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'Swimming',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'Wakeboarding & Waterskiing',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'Windsurfing',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Water Sports', 2 => 'Other',],
            [ 0 => 'Sports, Fitness & Recreation', 1 => 'Other Sporting Goods',],
            [ 0 => 'Stationery & Office Supplies',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Blank CDs and DVDs',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Filing and Binding Products',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Highlighters & Markers',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Notebooks & Writing Pads',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Office Electronics',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Office Electronics', 2 => 'Copiers',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Office Electronics', 2 => 'Fax Machines',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Office Electronics', 2 => 'Laminating',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Office Electronics', 2 => 'Shredders',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Office Electronics', 2 => 'Other',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Organizers',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Painting Supplies',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Paper',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Pens and Pencils',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Tapes, Adhesives & Fasteners',],
            [ 0 => 'Stationery & Office Supplies', 1 => 'Other',],
            [ 0 => 'Toys & Hobbies',],
            [ 0 => 'Toys & Hobbies', 1 => 'Educational Toys',],
            [ 0 => 'Toys & Hobbies', 1 => 'Outdoors',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'Drones',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'RC Airplanes',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'RC Boats',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'RC Cars & Trucks',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'RC Helicopters',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'RC Other',],
            [ 0 => 'Toys & Hobbies', 1 => 'Remote Control Toys', 2 => 'Parts & Accessories',],
            [ 0 => 'Toys & Hobbies', 1 => 'Soft and Stuffed Toys',],
            [ 0 => 'Toys & Hobbies', 1 => 'Toy Vehicles & Diecasts',],
            [ 0 => 'Toys & Hobbies', 1 => 'Other',],
            [ 0 => 'Video & Computer Gaming',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Accessories',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Accessories', 2 => 'Battery and Charger',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Accessories', 2 => 'Data and Power Cables',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Accessories', 2 => 'Game Controllers',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Accessories', 2 => 'Memory',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Accessories', 2 => 'Other',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Consoles',],
            [ 0 => 'Video & Computer Gaming', 1 => 'Games',],
            [ 0 => 'Other Stuff',],
            [ 0 => 'Housing & Real Estate',],
            [ 0 => 'Housing & Real Estate', 1 => 'Apartments & Houses for Rent',],
            [ 0 => 'Housing & Real Estate', 1 => 'Room for Rent',],
            [ 0 => 'Housing & Real Estate', 1 => 'Guest Houses & Short Stay Accomodation',],
            [ 0 => 'Housing & Real Estate', 1 => 'Kudhin Baithibbaadhinun',],
            [ 0 => 'Housing & Real Estate', 1 => 'Land For Sale & Lease',],
            [ 0 => 'Housing & Real Estate', 1 => 'Office & Commercial Space',],
            [ 0 => 'Housing & Real Estate', 1 => 'Roommates Wanted',],
            [ 0 => 'Housing & Real Estate', 1 => 'International',],
            [ 0 => 'Housing & Real Estate', 1 => 'International', 2 => 'Apartments & Houses for Rent',],
            [ 0 => 'Housing & Real Estate', 1 => 'International', 2 => 'Guest Houses & Short Stay Accomodation',],
            [ 0 => 'Housing & Real Estate', 1 => 'International', 2 => 'Kudhin Baithibbaadhinun',],
            [ 0 => 'Jobs',],
            [ 0 => 'Services',],
            [ 0 => 'Services', 1 => 'Architectural & Home Design',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Aerobics and Zumba Classes',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Beauty Services',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Gym and Fitness Studios',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Martial Arts Classes',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Personal Trainer',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Racket Stringing',],
            [ 0 => 'Services', 1 => 'Beauty, Sports and Wellness', 2 => 'Sports Coach',],
            [ 0 => 'Services', 1 => 'Business Services',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Accounting & Auditing',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Advertising & Marketing',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Business Consulting',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Cargo Handling & Logistics',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Computer & Telecom Networking',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Courier and Delivery',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Foreign Labor Recruitment & Services',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Legal',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Printing',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Secretarial Services',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Security Services',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Signboard Making',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Software Development',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Transport',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Web & Graphics Design',],
            [ 0 => 'Services', 1 => 'Business Services', 2 => 'Web Hosting',],
            [ 0 => 'Services', 1 => 'Domestic Services',],
            [ 0 => 'Services', 1 => 'Domestic Services', 2 => 'Babysitting and Child Care',],
            [ 0 => 'Services', 1 => 'Domestic Services', 2 => 'Cooking',],
            [ 0 => 'Services', 1 => 'Domestic Services', 2 => 'Laundry',],
            [ 0 => 'Services', 1 => 'Domestic Services', 2 => 'Maid',],
            [ 0 => 'Services', 1 => 'Event Services',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Cake',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Catering & Takeaway',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Corporate Event Planners',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Florists',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Function Venues',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Live Bands and Musicians',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Party Planners',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Party Supplies & Decoration',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Sound and Lighting',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Video & Photography',],
            [ 0 => 'Services', 1 => 'Event Services', 2 => 'Wedding Planners',],
            [ 0 => 'Services', 1 => 'Food Services',],
            [ 0 => 'Services', 1 => 'Healthcare Services',],
            [ 0 => 'Services', 1 => 'Industrial',],
            [ 0 => 'Services', 1 => 'Industrial', 2 => 'Boat Building & Related Services',],
            [ 0 => 'Services', 1 => 'Industrial', 2 => 'Welding & Engineering',],
            [ 0 => 'Services', 1 => 'Rental Services',],
            [ 0 => 'Services', 1 => 'Rental Services', 2 => 'Catering Utensils & Supplies',],
            [ 0 => 'Services', 1 => 'Rental Services', 2 => 'Chairs & Tables',],
            [ 0 => 'Services', 1 => 'Rental Services', 2 => 'Dhoani and Marine Vessels',],
            [ 0 => 'Services', 1 => 'Rental Services', 2 => 'Pickup & Heavy Vehicles',],
            [ 0 => 'Services', 1 => 'Rental Services', 2 => 'Tools & Equipment',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Aircon Servicing & Repair',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Building & Construction',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Camera Repair',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Carpentry',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Computer Repairs',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Dhonna Machine Maraamathukurun',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Electrical & Wiring',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Fen Motor Maraamathukurun',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Housekeeping & Cleaning',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Movers',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Pest Control',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Phone Servicing & Unlocking',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Plumbing',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Television Repair',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Vehicle Garage',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'Video Game Repair & Services',],
            [ 0 => 'Services', 1 => 'Repairs, Maintenance & Household Work', 2 => 'General / Other',],
            [ 0 => 'Services', 1 => 'Tailoring',],
            [ 0 => 'Services', 1 => 'Travel & Recreation',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Island Overview & Information',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Picnic, Fishing Trips & Other Activities',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Restaurants & Cafes',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Transport & Vehicle Rental',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Transport & Vehicle Rental', 3 => 'Bicycle Rental',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Transport & Vehicle Rental', 3 => 'Ferry & Naalu Boat',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Transport & Vehicle Rental', 3 => 'Motorcycle Rental',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Transport & Vehicle Rental', 3 => 'Speedboat & Dhoani Rental',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Transport & Vehicle Rental', 3 => 'Taxi & Car Rental',],
            [ 0 => 'Services', 1 => 'Travel & Recreation', 2 => 'Travel Packages',],
            [ 0 => 'Services', 1 => 'Tuition & Personal Development',],
            [ 0 => 'Services', 1 => 'Tuition & Personal Development', 2 => 'Cooking & Baking Classes',],
            [ 0 => 'Services', 1 => 'Tuition & Personal Development', 2 => 'Driving Classes',],
            [ 0 => 'Services', 1 => 'Tuition & Personal Development', 2 => 'Training',],
            [ 0 => 'Services', 1 => 'Tuition & Personal Development', 2 => 'Tuition',],
            [ 0 => 'Services', 1 => 'Other Services',],
            [ 0 => 'Services', 1 => 'Other Services', 2 => 'Audio & Video Recording',],
            [ 0 => 'Services', 1 => 'Other Services', 2 => 'Buying from Abroad',],
            [ 0 => 'Services', 1 => 'Other Services', 2 => 'Vehicle Registration & Roadworthiness',],
            [ 0 => 'Services', 1 => 'Other Services', 2 => 'Other Services',],
            [ 0 => 'Wanted',],
            [ 0 => 'Wanted', 1 => 'Books and Magazines',],
            [ 0 => 'Wanted', 1 => 'Clothing and Accessories',],
            [ 0 => 'Wanted', 1 => 'Computer Laptop and Accessories',],
            [ 0 => 'Wanted', 1 => 'Electronics',],
            [ 0 => 'Wanted', 1 => 'Mobile Phones and Accessories',],
            [ 0 => 'Wanted', 1 => 'Motorcycles- Cars and Accessories',],
            [ 0 => 'Wanted', 1 => 'Real Estate - Office Space and Commercial',],
            [ 0 => 'Wanted', 1 => 'Real Estate - Rooms and Apartment',],
            [ 0 => 'Wanted', 1 => 'Services',],
            [ 0 => 'Wanted', 1 => 'Sporting Goods',],
            [ 0 => 'Wanted', 1 => 'Toys Kids and Hobbies',],
            [ 0 => 'Wanted', 1 => 'Other Stuff',],
            [ 0 => 'Business Opportunities',],
            [ 0 => 'Business Opportunities', 1 => 'Business for Sale',],
            [ 0 => 'Business Opportunities', 1 => 'Websites for Sale',],
            [ 0 => 'Business Opportunities', 1 => 'Other',],
            [ 0 => 'Announcements & Events',],
            [ 0 => 'Announcements & Events', 1 => 'Announcements',],
            [ 0 => 'Announcements & Events', 1 => 'Lost and Found',],
            [ 0 => 'Announcements & Events', 1 => 'Promotions',],
            [ 0 => 'Announcements & Events', 1 => 'Trade Exhibitions & Fairs',],
            [ 0 => 'Announcements & Events', 1 => 'Other',],
            [ 0 => 'Free Stuff',],
        ];
    }
}
