<?php

namespace Database\Seeders;

use App\Models\Atoll;
use App\Models\Island;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class IslandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $islands = [
            ["name" => "Thuraakunu", "name_dhivehi" => "ތުރާކުނު"],
            ["name" => "Uligan", "name_dhivehi" => "އުލިގަން"],
            ["name" => "Berinmadhoo", "name_dhivehi" => "ބެރިންމަދޫ"],
            ["name" => "Hathifushi", "name_dhivehi" => "ހަތިފުށި"],
            ["name" => "Molhadhoo", "name_dhivehi" => "މޮޅަދޫ"],
            ["name" => "Hoarafushi", "name_dhivehi" => "ހޯރަފުށި"],
            ["name" => "Ihavandhoo", "name_dhivehi" => "އިހަވަންދޫ"],
            ["name" => "Kelaa", "name_dhivehi" => "ކެލާ"],
            ["name" => "Vashafaru", "name_dhivehi" => "ވަށަފަރު"],
            ["name" => "Dhidhdhoo", "name_dhivehi" => "ދިއްދޫ"],
            ["name" => "Filladhoo", "name_dhivehi" => "ފިއްލަދޫ"],
            ["name" => "Maarandhoo", "name_dhivehi" => "މާރަންދޫ"],
            ["name" => "Thakandhoo", "name_dhivehi" => "ތަކަންދޫ"],
            ["name" => "Utheemu", "name_dhivehi" => "އުތީމު"],
            ["name" => "Muraidhoo", "name_dhivehi" => "މުރައިދޫ"],
            ["name" => "Baarah", "name_dhivehi" => "ބާރަށް"],
            ["name" => "Maafahi", "name_dhivehi" => "މާފަހި"],
            ["name" => "Alidhoo", "name_dhivehi" => "އަލިދޫ"],
            ["name" => "Huvahandhoo", "name_dhivehi" => "ހުވަހަންދޫ"],
            ["name" => "Dhonakulhi", "name_dhivehi" => "ދޮނަކުޅި"],
            ["name" => "Beenaafushi", "name_dhivehi" => "ބީނާފުށި"],
            ["name" => "Dhapparuhuraa", "name_dhivehi" => "ދައްޕަރުހުރާ"],
            ["name" => "Dhigufaruhuraa", "name_dhivehi" => "ދިގުފަރުހުރާ"],
            ["name" => "Gaafushi", "name_dhivehi" => "ގާފުށި"],
            ["name" => "Gaamathikulhudhoo", "name_dhivehi" => "ގާމަތިކުޅުދޫ"],
            ["name" => "Gallandhoo", "name_dhivehi" => "ގައްލަންދޫ"],
            ["name" => "Govvaafushi", "name_dhivehi" => "ގޮށްވާފުށި"],
            ["name" => "Innafinolhu", "name_dhivehi" => "އިންނަފިނޮޅު"],
            ["name" => "Kudafinolhu", "name_dhivehi" => "ކުޑަފިނޮޅު"],
            ["name" => "Maafari", "name_dhivehi" => "މާފަރި"],
            ["name" => "Maafinolhu", "name_dhivehi" => "މާފިނޮޅު"],
            ["name" => "Madulu", "name_dhivehi" => "މަޑުލު"],
            ["name" => "Manafaru", "name_dhivehi" => "މަނަފަރު"],
            ["name" => "Matheerah", "name_dhivehi" => "މަތީރަށް"],
            ["name" => "Medhafushi", "name_dhivehi" => "މެދަފުށި"],
            ["name" => "Mulidhoo", "name_dhivehi" => "މުލިދޫ"],
            ["name" => "Naridhoo", "name_dhivehi" => "ނަރިދޫ"],
            ["name" => "Ubulifinolhu", "name_dhivehi" => "އުނބުލިފިނޮޅު"],
            ["name" => "Umaraiyfinolhu", "name_dhivehi" => "އުމަރަތްފިނޮޅު"],
            ["name" => "Vangaaru", "name_dhivehi" => "ވަނގާރު"],
            ["name" => "Velifinolhu", "name_dhivehi" => "ވެލިފިނޮޅު"],
            ["name" => "Faridhoo", "name_dhivehi" => "ފަރިދޫ"],
            ["name" => "Hondaidhoo", "name_dhivehi" => "ހޮނޑައިދޫ"],
            ["name" => "Hanimaadhoo", "name_dhivehi" => "ހަނިމާދޫ"],
            ["name" => "Finey", "name_dhivehi" => "ފިނޭ"],
            ["name" => "Naivaadhoo", "name_dhivehi" => "ނައިވާދޫ"],
            ["name" => "Hirimaradhoo", "name_dhivehi" => "ހިރިމަރަދޫ"],
            ["name" => "Nolhivaranfaru", "name_dhivehi" => "ނޮޅިވަރަންފަރު"],
            ["name" => "Nellaidhoo", "name_dhivehi" => "ނެއްލައިދޫ"],
            ["name" => "Nolhivaram", "name_dhivehi" => "ނޮޅިވަރަމް"],
            ["name" => "Kurinbi", "name_dhivehi" => "ކުރިނބި"],
            ["name" => "Kunburudhoo", "name_dhivehi" => "ކުނބުރުދޫ"],
            ["name" => "Kulhudhuffushi", "name_dhivehi" => "ކުޅުދުއްފުށި"],
            ["name" => "Kumundhoo", "name_dhivehi" => "ކުމުންދޫ"],
            ["name" => "Neykurendhoo", "name_dhivehi" => "ނޭކުރެންދޫ"],
            ["name" => "Vaikaradhoo", "name_dhivehi" => "ވައިކަރަދޫ"],
            ["name" => "Maavaidhoo", "name_dhivehi" => "މާވައިދޫ"],
            ["name" => "Makunudhoo", "name_dhivehi" => "މަކުނުދޫ"],
            ["name" => "Vaikaramuraidhoo", "name_dhivehi" => "ވައިކަރަމުރާދޫ"],
            ["name" => "Theefaridhoo", "name_dhivehi" => "ތީފަރިދޫ"],
            ["name" => "Dhipparufushi", "name_dhivehi" => "ދިއްޕަރުފުށި"],
            ["name" => "Fenboahuraa", "name_dhivehi" => "ފެންބޯހުރާ"],
            ["name" => "Hirinaidhoo", "name_dhivehi" => "ހިރިނައިދޫ"],
            ["name" => "Hodaafushi", "name_dhivehi" => "ހޮނޑާފުށި"],
            ["name" => "Innafushi", "name_dhivehi" => "އިންނަފުށި"],
            ["name" => "Kanamana", "name_dhivehi" => "ކަނަމަނަ"],
            ["name" => "Kandinmaahuraa", "name_dhivehi" => "ކަނޑިންމާހުރާ"],
            ["name" => "Kattalafushi", "name_dhivehi" => "ކައްޓަލަފުށި"],
            ["name" => "Keylakunu", "name_dhivehi" => "ކޭލަކުނު"],
            ["name" => "Kudafaru", "name_dhivehi" => "ކުޑަފަރު"],
            ["name" => "Kudamuraidhoo", "name_dhivehi" => "ކުޑަމުރައިދޫ"],
            ["name" => "Muiri", "name_dhivehi" => "މުއިރު"],
            ["name" => "Naagoashi", "name_dhivehi" => "ނާގޯށި"],
            ["name" => "Rahburi", "name_dhivehi" => "ރަށްބުރި"],
            ["name" => "Rasfushi", "name_dhivehi" => "ރަސްފުށި"],
            ["name" => "Ruffushi", "name_dhivehi" => "ރުއްފުށި"],
            ["name" => "Veligandu", "name_dhivehi" => "ވެލިގަނޑު"],
            ["name" => "Kanditheemu", "name_dhivehi" => "ކަނޑިތީމު"],
            ["name" => "Noomaraa", "name_dhivehi" => "ނޫމަރާ"],
            ["name" => "Goidhoo", "name_dhivehi" => "ގޮއިދޫ"],
            ["name" => "Feydhoo", "name_dhivehi" => "ފޭދޫ"],
            ["name" => "Feevah", "name_dhivehi" => "ފީވައް"],
            ["name" => "Bilehffahi", "name_dhivehi" => "ބިލެތްފަހި"],
            ["name" => "Foakaidhoo", "name_dhivehi" => "ފޯކައިދޫ"],
            ["name" => "Narudhoo", "name_dhivehi" => "ނަރުދޫ"],
            ["name" => "Maakandoodhoo", "name_dhivehi" => "މާކަނޑޫދޫ"],
            ["name" => "Maroshi", "name_dhivehi" => "މަރޮށި"],
            ["name" => "Lhaimagu", "name_dhivehi" => "ޅައިމަގު"],
            ["name" => "Firubaidhoo", "name_dhivehi" => "ފިރުނބައިދޫ"],
            ["name" => "Komandoo", "name_dhivehi" => "ކޮމަންޑޫ"],
            ["name" => "Maaungoodhoo", "name_dhivehi" => "މާއުނގޫދޫ"],
            ["name" => "Funadhoo", "name_dhivehi" => "ފުނަދޫ"],
            ["name" => "Milandhoo", "name_dhivehi" => "މިލަންދޫ"],
            ["name" => "Nilandhoo", "name_dhivehi" => "ނިލަންދޫ"],
            ["name" => "Keekimini", "name_dhivehi" => "ކީކިމިނި"],
            ["name" => "Bisalhaahuraa", "name_dhivehi" => "ބިސްއަޅާހުރާ"],
            ["name" => "Boduhuraa", "name_dhivehi" => "ބޮޑުހުރާ"],
            ["name" => "Bolissafaru", "name_dhivehi" => "ބޮލިއްސަރު"],
            ["name" => "Dhigurah", "name_dhivehi" => "ދިގުރަށް"],
            ["name" => "Dhiguvelidhoo", "name_dhivehi" => "ދިގުވެލިދޫ"],
            ["name" => "Dholhiyadhoo", "name_dhivehi" => "ދޮޅިޔަދޫ"],
            ["name" => "Dhonvelihuraa", "name_dhivehi" => "ދޮންވެލިހުރާ"],
            ["name" => "Dolhiyadhoo Kudarah", "name_dhivehi" => "ދޮޅިޔަދޫކުޑަރަށް"],
            ["name" => "Eriadhoo", "name_dhivehi" => "އެރިއަދޫ"],
            ["name" => "Eskasdhoo", "name_dhivehi" => "އެސްކަސްދޫ"],
            ["name" => "Farukolhu", "name_dhivehi" => "ފަރުކޮޅު"],
            ["name" => "Fushifaru", "name_dhivehi" => "ފުށިފަރު"],
            ["name" => "Gaakoshibee", "name_dhivehi" => "ގާކޮށިބީ"],
            ["name" => "Gallaidhoo", "name_dhivehi" => "ގައްލައިދޫ"],
            ["name" => "Hahfathigadu", "name_dhivehi" => "ހަތްފަތިގަނޑު"],
            ["name" => "Hirubadhoo", "name_dhivehi" => "ހިނރުބަދޫ"],
            ["name" => "Hurasfaru", "name_dhivehi" => "ހުރަސްފަރު"],
            ["name" => "Ka'baalifaru", "name_dhivehi" => "ކަނބާލިފަރު"],
            ["name" => "Kakaaeriadhoo", "name_dhivehi" => "ކަކާއެރިއަދޫ"],
            ["name" => "Kudadhoo", "name_dhivehi" => "ކުޑަދޫ"],
            ["name" => "Kudafarufinolhu", "name_dhivehi" => "ކުޑަފަރުފިނޮޅު"],
            ["name" => "Kudafaruhuraa", "name_dhivehi" => "ކުޑަފަރުހުރާ"],
            ["name" => "Kudafunadhoo", "name_dhivehi" => "ކުޑަފުނަދޫ"],
            ["name" => "Kudalhaimendhoo", "name_dhivehi" => "ކުޑަޅައިމެންދޫ"],
            ["name" => "Madidhoo", "name_dhivehi" => "މަޑިދޫ"],
            ["name" => "Madikuredhdhoo", "name_dhivehi" => "މަޑިކުރެއްދޫ"],
            ["name" => "Mathikomandoo", "name_dhivehi" => "މަތިކޮމަންޑޫ"],
            ["name" => "Medhukuburudhoo", "name_dhivehi" => "މެދުކުނބުރުދޫ"],
            ["name" => "Medhurah", "name_dhivehi" => "މެދުރަށް"],
            ["name" => "Migoodhoo", "name_dhivehi" => "މިގޫދޫ"],
            ["name" => "Muleehuraa", "name_dhivehi" => "މުލީހުރާ"],
            ["name" => "Naainfaru", "name_dhivehi" => "ނާއިންފަރު"],
            ["name" => "Naalaahuraa", "name_dhivehi" => "ނާލާހުރާ"],
            ["name" => "Nalandhoo", "name_dhivehi" => "ނަލަންދޫ"],
            ["name" => "Naruribudhoo", "name_dhivehi" => "ނަރުރިނބުދޫ"],
            ["name" => "Neyo", "name_dhivehi" => "ނެޔޮ"],
            ["name" => "Vagaru", "name_dhivehi" => "ވަގަރު"],
            ["name" => "Henbandhoo", "name_dhivehi" => "ހެނބަދޫ"],
            ["name" => "Kendhikolhudhoo", "name_dhivehi" => "ކެނދިކޮޅުދޫ"],
            ["name" => "Tholhendhoo", "name_dhivehi" => "ތޮޅެންދޫ"],
            ["name" => "Maalhendhoo", "name_dhivehi" => "މާޅެންދޫ"],
            ["name" => "Kudafari", "name_dhivehi" => "ކުޑަފަރީ"],
            ["name" => "Landhoo", "name_dhivehi" => "ލަންދޫ"],
            ["name" => "Maafaru", "name_dhivehi" => "މާފަރު"],
            ["name" => "Lhohi", "name_dhivehi" => "ޅޮހި"],
            ["name" => "Miladhoo", "name_dhivehi" => "މިލަދޫ"],
            ["name" => "Magoodhoo", "name_dhivehi" => "މަގޫދޫ"],
            ["name" => "Manadhoo", "name_dhivehi" => "މަނަދޫ"],
            ["name" => "Holhudhoo", "name_dhivehi" => "ހޮޅުދޫ"],
            ["name" => "Fodhdhoo", "name_dhivehi" => "ފޮއްދޫ"],
            ["name" => "Velidhoo", "name_dhivehi" => "ވެލިދޫ"],
            ["name" => "Aarah", "name_dhivehi" => "އާރަށް"],
            ["name" => "Badaidhidhdhoo", "name_dhivehi" => "ބަނޑިއްދޫ"],
            ["name" => "Bodufushi", "name_dhivehi" => "ބޮޑުފުށި"],
            ["name" => "Bodulhaimendhoo", "name_dhivehi" => "ބޮޑުޅައިމެންދޫ"],
            ["name" => "Bomasdhoo", "name_dhivehi" => "ބޮމަސްދޫ"],
            ["name" => "Burehifasdhoo", "name_dhivehi" => "ބުރެހިފަސްދޫ"],
            ["name" => "Dheefuram", "name_dhivehi" => "ދީފުރަމް"],
            ["name" => "Dhekenanfaru", "name_dhivehi" => "ދެކެނަންފަރު"],
            ["name" => "Dhigurah", "name_dhivehi" => "ދިގުރަށް"],
            ["name" => "Dhonaerikandoodhoo", "name_dhivehi" => "ދޮނައެރިކަންދޫދޫ"],
            ["name" => "Edhdhuffaru Mairah", "name_dhivehi" => "އެއްދުފަރު މައިރަށް"],
            ["name" => "Ekulhivaru", "name_dhivehi" => "އެކުޅިވަރު"],
            ["name" => "Erruhhuraa", "name_dhivehi" => "އެއްރުށްހުރާ"],
            ["name" => "Farumuli", "name_dhivehi" => "ފަރުމުލި"],
            ["name" => "Felivaru", "name_dhivehi" => "ފެލިވަރު"],
            ["name" => "Felivarukudarah", "name_dhivehi" => "ފެލިވަރުކުޑަރަށް"],
            ["name" => "Fohdhipparu", "name_dhivehi" => "ފޮށްދިއްޕަރު"],
            ["name" => "Fushivelavaru", "name_dhivehi" => "ފުށިވެލަވަރު"],
            ["name" => "Goabilivaadhoo", "name_dhivehi" => "ގޯނބިލިވާދޫ"],
            ["name" => "Holhumeedhoo", "name_dhivehi" => "ހޮޅުމީދޫ"],
            ["name" => "Huivani", "name_dhivehi" => "ހުއިވަނި"],
            ["name" => "Hulhudhdhoo", "name_dhivehi" => "ހުޅުއްދޫ"],
            ["name" => "Huvadhumaavattaru", "name_dhivehi" => "ހުވަނދުމާވައްޓަރު"],
            ["name" => "Inguraidhoo", "name_dhivehi" => "އިނގުރައިދޫ"],
            ["name" => "Kaalhugemendhoo", "name_dhivehi" => "ކާޅުގެމެންދޫ"],
            ["name" => "Kadinmaahuraa", "name_dhivehi" => "ކަނޑިމާހުރާ"],
            ["name" => "Kafakomandoo", "name_dhivehi" => "ކަފަކޮމަންޑޫ"],
            ["name" => "Kalaidhoo", "name_dhivehi" => "ކަލައިދޫ"],
            ["name" => "Karinma", "name_dhivehi" => "ކަރިންމާ"],
            ["name" => "Karinmavattaru", "name_dhivehi" => "ކަރިންމަވައްޓަރު"],
            ["name" => "Kedhivaru", "name_dhivehi" => "ކެނދިވަރު"],
            ["name" => "Kolhufushi", "name_dhivehi" => "ކޮޅުފުށި"],
            ["name" => "Kudafunafaru", "name_dhivehi" => "ކުޑަފުނަފަރު"],
            ["name" => "Kudafushi", "name_dhivehi" => "ކުޑަފުށި"],
            ["name" => "Kunnumalei", "name_dhivehi" => "ކުންނުމަލެއި"],
            ["name" => "Kuramaadhoo", "name_dhivehi" => "ކުރަނމާދޫ"],
            ["name" => "Kuredhivaru", "name_dhivehi" => "ކުރެދިވަރު"],
            ["name" => "Loafaru", "name_dhivehi" => "ލޯފަރު"],
            ["name" => "Maafunafaru", "name_dhivehi" => "މާފުނަފަރު"],
            ["name" => "Maakanaafushi", "name_dhivehi" => "މާކަނާފުށި"],
            ["name" => "Maakurandhoo", "name_dhivehi" => "މާކުރަންދޫ"],
            ["name" => "Maavandhoo", "name_dhivehi" => "މާވަންދޫ"],
            ["name" => "Maavelavaru", "name_dhivehi" => "މާވެލަވަރު"],
            ["name" => "Medhafushi", "name_dhivehi" => "މެދަފުށި"],
            ["name" => "Medhufaru", "name_dhivehi" => "މެދުފަރު"],
            ["name" => "Minaavaru", "name_dhivehi" => "މިނާވަރު"],
            ["name" => "Orimasvaru", "name_dhivehi" => "އޮރިމަސްވަރު"],
            ["name" => "Orivaru", "name_dhivehi" => "އޮރިވަރު"],
            ["name" => "Orivarukudarah", "name_dhivehi" => "އޮރިވަރުކުޑަރަށް"],
            ["name" => "Raafushi", "name_dhivehi" => "ރާފުށި"],
            ["name" => "Raalhugadu", "name_dhivehi" => "ރާޅުގަޑު"],
            ["name" => "Raalhulaakolhu", "name_dhivehi" => "ރާޅުލާކޮޅު"],
            ["name" => "Randheli", "name_dhivehi" => "ރަންދެލި"],
            ["name" => "Thaburudhoo", "name_dhivehi" => "ތަނބުރުދޫ"],
            ["name" => "Thaburudhuffushi", "name_dhivehi" => "ތަނބުރުދުއްފުށި"],
            ["name" => "Tholhendhoo", "name_dhivehi" => "ތޮޅެންދޫ"],
            ["name" => "Thoshigandukolhu", "name_dhivehi" => "ތޮށިގަނޑުކޮޅު"],
            ["name" => "Vavathi", "name_dhivehi" => "ވަވަތި"],
            ["name" => "Vihafaru", "name_dhivehi" => "ވިހަފަރު"],
            ["name" => "Vihafarufinolhu", "name_dhivehi" => "ވިހަފަރުފިނޮޅު"],
            ["name" => "Alifushi", "name_dhivehi" => "އަލިފުށި"],
            ["name" => "Vaadhoo", "name_dhivehi" => "ވާދޫ"],
            ["name" => "Rasgetheemu", "name_dhivehi" => "ރަސްގެތީމު"],
            ["name" => "Angolhitheemu", "name_dhivehi" => "އަނގޮޅިތީމު"],
            ["name" => "Gaaudoodhoo", "name_dhivehi" => "ގާއުނޑޫދޫ"],
            ["name" => "Ungoofaaru", "name_dhivehi" => "އުނގޫފާރު"],
            ["name" => "Kadholhudhoo", "name_dhivehi" => "ކަނދޮޅުދޫ"],
            ["name" => "Maakurathu", "name_dhivehi" => "މާކުރަތު"],
            ["name" => "Rasmaadhoo", "name_dhivehi" => "ރަސްމާދޫ"],
            ["name" => "Innamaadhoo", "name_dhivehi" => "އިންނަމާދޫ"],
            ["name" => "Maduvvari", "name_dhivehi" => "މަޑުއްވަރީ"],
            ["name" => "Inguraidhoo", "name_dhivehi" => "އިނގުރައިދޫ"],
            ["name" => "Fainu", "name_dhivehi" => "ފައިނު"],
            ["name" => "Meedhoo", "name_dhivehi" => "މީދޫ"],
            ["name" => "Kinolhas", "name_dhivehi" => "ކިނޮޅަސް"],
            ["name" => "Hulhudhuffaaru", "name_dhivehi" => "ހުޅުދުއްފާރު"],
            ["name" => "Ifuru", "name_dhivehi" => "އިފުރު"],
            ["name" => "Meedhupparu", "name_dhivehi" => "މީދުއްޕަރު"],
            ["name" => "Aarah", "name_dhivehi" => "އާރަށް"],
            ["name" => "Angaagiri", "name_dhivehi" => "އަންގާގިރި"],
            ["name" => "Arilundhoo", "name_dhivehi" => "އަރިލުންދޫ"],
            ["name" => "Badaveri", "name_dhivehi" => "ބަނޑަވެރި"],
            ["name" => "Bodufarufinolhu", "name_dhivehi" => "ބޮޑުފަރުފިނޮޅު"],
            ["name" => "Bodufenmaaembudhoo", "name_dhivehi" => "ބޮޑުފެންމާއެނބޫދޫ"],
            ["name" => "Bodufushi", "name_dhivehi" => "ބޮޑުފުށި"],
            ["name" => "Boduhuraa", "name_dhivehi" => "ބޮޑުހުރާ"],
            ["name" => "Dheburidheythereyvaadhoo", "name_dhivehi" => "ދެބުރިދޭތެރޭވާދޫ"],
            ["name" => "Dhekunumaafaru", "name_dhivehi" => "ދެކުނުމާފަރު"],
            ["name" => "Dhigali", "name_dhivehi" => "ދިގަލި"],
            ["name" => "Dhikkuredhdhoo", "name_dhivehi" => "ދިއްކުރެއްދޫ"],
            ["name" => "Dhinnaafushi", "name_dhivehi" => "ދިންނާފުށި"],
            ["name" => "Dhoragali", "name_dhivehi" => "ދޮރަނގަލި"],
            ["name" => "Dhuvaafaru", "name_dhivehi" => "ދުވާފަރު"],
            ["name" => "Dhuvaafaruhuraa", "name_dhivehi" => "ދުވާފަރުހުރާ"],
            ["name" => "Ehthigandujehihuraa", "name_dhivehi" => "އެތިގަނޑުޖެހިހުރާ"],
            ["name" => "Ehthigili", "name_dhivehi" => "އެއްތިގިނލި"],
            ["name" => "Ekurufushifinolhu", "name_dhivehi" => "އެކުރުފުށިފިނޮޅު"],
            ["name" => "Faarufushi", "name_dhivehi" => "ފާރުފުށި"],
            ["name" => "Fasgandufaru", "name_dhivehi" => "ފަސްގަނޑުފަރު"],
            ["name" => "Fasmendhoo", "name_dhivehi" => "ފަސްމެންދޫ"],
            ["name" => "Fenfushi", "name_dhivehi" => "ފެންފުށި"],
            ["name" => "Filaidhoo", "name_dhivehi" => "ފިލައިދޫ"],
            ["name" => "Fuggiri", "name_dhivehi" => "ފުއްގިރި"],
            ["name" => "Furaveri", "name_dhivehi" => "ފުރަވެރި"],
            ["name" => "Gaaudoodhoo", "name_dhivehi" => "ގާއުނޑޫދޫ"],
            ["name" => "Gemana", "name_dhivehi" => "ގެމަނަ"],
            ["name" => "Giraavaaru", "name_dhivehi" => "ގިރާވަރު"],
            ["name" => "Goiymaru", "name_dhivehi" => "ގޮތްމަރު"],
            ["name" => "Goyyafaru", "name_dhivehi" => "ގޮތްޔަފަރު"],
            ["name" => "Gubolhi", "name_dhivehi" => "ގުނބޮޅި"],
            ["name" => "Bodu Haiykodi", "name_dhivehi" => "ބޮޑުހަތްކޮޑި"],
            ["name" => "Hiboodhoo", "name_dhivehi" => "ހިނބޫދޫ"],
            ["name" => "Hiraveri", "name_dhivehi" => "ހިރަވެރި"],
            ["name" => "Hulhudhoo", "name_dhivehi" => "ހުޅުދޫ"],
            ["name" => "Huruvalhi", "name_dhivehi" => "ހުރުވަޅި"],
            ["name" => "Kadoogadu", "name_dhivehi" => "ކަޑޫގަނޑު"],
            ["name" => "Kandhoomeehunge lhaabugali", "name_dhivehi" => "ކަންދޫމީހުންގެޅާބުގަލި"],
            ["name" => "Kothaafaru", "name_dhivehi" => "ކޮތާފަރު"],
            ["name" => "Kottefaru", "name_dhivehi" => "ކޮށްޓެފަރު"],
            ["name" => "Kudafenmaaembudhoo", "name_dhivehi" => "ކުޑަފެންމާއެނބޫދޫ"],
            ["name" => "Kudafushi", "name_dhivehi" => "ކުޑަފުށި"],
            ["name" => "Kudakurathu", "name_dhivehi" => "ކުޑަކުރަތު"],
            ["name" => "Kudalhosgiri", "name_dhivehi" => "ކުޑަޅޮސްގިރި"],
            ["name" => "Kudathulhaadhoo", "name_dhivehi" => "ކުޑަތުޅާދޫ"],
            ["name" => "Kukulhudhoo", "name_dhivehi" => "ކުކުޅުދޫ"],
            ["name" => "Kuredhdhoo", "name_dhivehi" => "ކުރެއްދޫ"],
            ["name" => "Kuroshigiri", "name_dhivehi" => "ކުރޮށިގިރި"],
            ["name" => "Lhaabugali", "name_dhivehi" => "ޅާނބުގަލި"],
            ["name" => "Lhohi", "name_dhivehi" => "ޅޮހި"],
            ["name" => "Liboakandhoo", "name_dhivehi" => "ލިބޯކަންދޫ"],
            ["name" => "Lundhufushi", "name_dhivehi" => "ލުންދުފުށި"],
            ["name" => "Maamingili", "name_dhivehi" => "މާމިނގިލި"],
            ["name" => "Maamunagau", "name_dhivehi" => "މާމުނަގައު"],
            ["name" => "Maamunagaufinolhu", "name_dhivehi" => "މާމުނަގައުފިނޮޅު"],
            ["name" => "Maanenfushi", "name_dhivehi" => "މާމެންފުށި"],
            ["name" => "Maashigiri", "name_dhivehi" => "މާށިގިރި"],
            ["name" => "Madivaafaru", "name_dhivehi" => "މަޑިވާފަރު"],
            ["name" => "Mahidhoo", "name_dhivehi" => "މަހިދޫ"],
            ["name" => "Meedhupparu", "name_dhivehi" => "މީދުއްޕަރު"],
            ["name" => "Minaadhoo", "name_dhivehi" => "މިނާދޫ"],
            ["name" => "Mullaafushi", "name_dhivehi" => "މުއްލާފުށި"],
            ["name" => "Muravandhoo", "name_dhivehi" => "މުރަވަންދޫ"],
            ["name" => "Neyo", "name_dhivehi" => "ނެޔޮ"],
            ["name" => "Orimasfushi", "name_dhivehi" => "އޮރިމަސްފުށި"],
            ["name" => "Thaavathaa", "name_dhivehi" => "ތާވަތާ"],
            ["name" => "Ufulandhoo", "name_dhivehi" => "އުފުލަންދޫ"],
            ["name" => "Ugulu", "name_dhivehi" => "އުނގުލު"],
            ["name" => "Uthurumaafaru", "name_dhivehi" => "އުތުރުމާފަރު"],
            ["name" => "Vaffushihuraa", "name_dhivehi" => "ވަށްފުށިހުރާ"],
            ["name" => "Vahfushi", "name_dhivehi" => "ވަށްފުށި"],
            ["name" => "Vandhoo", "name_dhivehi" => "ވަންދޫ"],
            ["name" => "Veyveh", "name_dhivehi" => "ވޭވަށް"],
            ["name" => "Villingili", "name_dhivehi" => "ވިލިނގިލި"],
            ["name" => "Kudarikilu", "name_dhivehi" => "ކުޑަރިކިލު"],
            ["name" => "Kamadhoo", "name_dhivehi" => "ކަމަދޫ"],
            ["name" => "Kendhoo", "name_dhivehi" => "ކެންދޫ"],
            ["name" => "Maaddoo", "name_dhivehi" => "މާއްޑޫ"],
            ["name" => "Udoodhoo", "name_dhivehi" => "އުދޫދޫ"],
            ["name" => "Kihaadhoo", "name_dhivehi" => "ކިހާދޫ"],
            ["name" => "Dhonfanu", "name_dhivehi" => "ދޮންފަނު"],
            ["name" => "Dharavandhoo", "name_dhivehi" => "ދަރަވަންދޫ"],
            ["name" => "Maalhos", "name_dhivehi" => "މާޅޮސް"],
            ["name" => "Eydhafushi", "name_dhivehi" => "އޭދަފުށި"],
            ["name" => "Funadhoo", "name_dhivehi" => "ފުނަދޫ"],
            ["name" => "Thulhaadhoo", "name_dhivehi" => "ތުޅާދޫ"],
            ["name" => "Hithaadhoo", "name_dhivehi" => "ހިތާދޫ"],
            ["name" => "Fulhadhoo", "name_dhivehi" => "ފުޅަދޫ"],
            ["name" => "Fehendhoo", "name_dhivehi" => "ފެހެންދޫ"],
            ["name" => "Goidhoo", "name_dhivehi" => "ގޮއިދޫ"],
            ["name" => "Landaagiraavaru", "name_dhivehi" => "ލަނޑާގިރާވަރު"],
            ["name" => "Dhunikolhu", "name_dhivehi" => "ދުނިކޮޅު"],
            ["name" => "Kihaadhuffaru", "name_dhivehi" => "ކިހާދުއްފަރު"],
            ["name" => "Fonimagoodhoo", "name_dhivehi" => "ފޮނިމަގޫދޫ"],
            ["name" => "Kunfunadhoo", "name_dhivehi" => "ކުންފުނަދޫ"],
            ["name" => "Horubadhoo", "name_dhivehi" => "ހޮރުބަނދޫ"],
            ["name" => "Ahivahfushi", "name_dhivehi" => "އަހިވަށްފުށި"],
            ["name" => "Aidhoo", "name_dhivehi" => "އައިދޫ"],
            ["name" => "Anhenunfushi", "name_dhivehi" => "އަންހެންފުށި"],
            ["name" => "Balhufinolhu", "name_dhivehi" => "ބަޅުފިނޮޅު"],
            ["name" => "Bathalaa", "name_dhivehi" => "ބަތަލާ"],
            ["name" => "Bathalaahuraa", "name_dhivehi" => "ބަތަލާހުރާ"],
            ["name" => "Boadhaafusheefinolhu", "name_dhivehi" => "ބޯދާފުށީފިނޮޅު"],
            ["name" => "Bodufinolhu", "name_dhivehi" => "ބޮޑުފިނޮޅު"],
            ["name" => "Boifushi", "name_dhivehi" => "ބޮތްފުށި"],
            ["name" => "Dhakandhoo", "name_dhivehi" => "ދަކަނދޫ"],
            ["name" => "Dhandhoo", "name_dhivehi" => "ދަންދޫ"],
            ["name" => "Dhigudhefaru", "name_dhivehi" => "ދިގުދެފަރު"],
            ["name" => "Dhigufaruvinagandu", "name_dhivehi" => "ދިގުފަރުވިނަގަނޑު"],
            ["name" => "Dhoogandufinolhu", "name_dhivehi" => "ދޫގަނޑުފިނޮޅު"],
            ["name" => "Embudhoo", "name_dhivehi" => "އެނބޫދޫ"],
            ["name" => "Fareedhaafinolhu", "name_dhivehi" => "ފަރީދާފިނޮޅު"],
            ["name" => "Fares", "name_dhivehi" => "ފަރެސް"],
            ["name" => "Fehenfaru", "name_dhivehi" => "ފެހެންފަރު"],
            ["name" => "Finolhas", "name_dhivehi" => "ފިނޮޅަސް"],
            ["name" => "Funadhoo", "name_dhivehi" => "ފުނަދޫ"],
            ["name" => "Gaagadufaruhuraa", "name_dhivehi" => "ގާގަނޑުފަރުހުރާ"],
            ["name" => "Gaaviligili", "name_dhivehi" => "ގާވިލިނގިލި"],
            ["name" => "Gemendhoo", "name_dhivehi" => "ގެމެންދޫ"],
            ["name" => "Hanifaru", "name_dhivehi" => "ހަނިފަރު"],
            ["name" => "Hibalhidhoo", "name_dhivehi" => "ހިބަޅިދޫ"],
            ["name" => "Hirundhoo", "name_dhivehi" => "ހިރުނދޫ"],
            ["name" => "Hulhudhoo", "name_dhivehi" => "ހުޅުދޫ"],
            ["name" => "Innafushi", "name_dhivehi" => "އިންނަފުށި"],
            ["name" => "Kanufusheefinolhu", "name_dhivehi" => "ކަނުފުށީފިނޮޅު"],
            ["name" => "Kanufusheegaathufinolhu", "name_dhivehi" => "ކަނުފުށީގާތުފިނޮޅު"],
            ["name" => "Kanufushi", "name_dhivehi" => "ކަނުފުށި"],
            ["name" => "Kashidhoo", "name_dhivehi" => "ކަށިދޫ"],
            ["name" => "Kashidhuhfarufinolhu", "name_dhivehi" => "ކަށިދުއްފަރުފިނޮޅު"],
            ["name" => "Keyodhoo", "name_dhivehi" => "ކެޔޮދޫ"],
            ["name" => "Kihavah Haruvalhi", "name_dhivehi" => "ކިހައްވަށްހަރުވަޅި"],
            ["name" => "Kudadhoo", "name_dhivehi" => "ކުޑަދޫ"],
            ["name" => "Maaddoo", "name_dhivehi" => "މާއްޑޫ"],
            ["name" => "Maaddoohulhudhoo", "name_dhivehi" => "މާއްޑޫހުޅުދޫ"],
            ["name" => "Maafusheefinolhu", "name_dhivehi" => "މާފުށީފިނޮޅު"],
            ["name" => "Maamaduvvaree", "name_dhivehi" => "މާމަޑުއްވަރީ"],
            ["name" => "Maarikili", "name_dhivehi" => "މާރިކިލި"],
            ["name" => "Madhirivaadhoo", "name_dhivehi" => "މާދިރިވާދޫ"],
            ["name" => "Medhufinolhu", "name_dhivehi" => "މެދުފިނޮޅު"],
            ["name" => "Medhufinolhu", "name_dhivehi" => "މެދުފިނޮޅު"],
            ["name" => "Mendhoo", "name_dhivehi" => "މެންދޫ"],
            ["name" => "Milaidhoo", "name_dhivehi" => "މިލައިދޫ"],
            ["name" => "Miriandhoo", "name_dhivehi" => "މިރިއަންދޫ"],
            ["name" => "Mudhdhoo", "name_dhivehi" => "މުއްދޫ"],
            ["name" => "Muthaafushi", "name_dhivehi" => "މުތާފުށި"],
            ["name" => "Nelivarufinolhu", "name_dhivehi" => "ނެލިވަރުފިނޮޅު"],
            ["name" => "Nibiligaa", "name_dhivehi" => "ނިބިލިގާ"],
            ["name" => "Olhugiri", "name_dhivehi" => "އޮޅުގިރި"],
            ["name" => "Fulhadhoo rahkairi finolhu", "name_dhivehi" => "ފުޅަދޫ ރަށްކައިރި ފިނޮޅު"],
            ["name" => "Thiladhoo", "name_dhivehi" => "ތިލަދޫ"],
            ["name" => "Udoodhoo", "name_dhivehi" => "އުނޑޫދޫ"],
            ["name" => "Ufuligiri", "name_dhivehi" => "އުފުލިގިރި"],
            ["name" => "Vakkaru", "name_dhivehi" => "ވައްކަރު"],
            ["name" => "Veyofushi", "name_dhivehi" => "ވެޔޮފުށި"],
            ["name" => "Vinaneiyfaruhuraa", "name_dhivehi" => "ވިނަނެތްފަރުހުރާ"],
            ["name" => "Voavah", "name_dhivehi" => "ވޯވައް"],
            ["name" => "Hinnavaru", "name_dhivehi" => "ހިންނަވަރު"],
            ["name" => "Naifaru", "name_dhivehi" => "ނައިފަރު"],
            ["name" => "Kurendhoo", "name_dhivehi" => "ކުރެންދޫ"],
            ["name" => "Olhuvelifushi", "name_dhivehi" => "އޮޅުވެލިފުށި"],
            ["name" => "Maafilaafushi", "name_dhivehi" => "މާފިލާފުށި"],
            ["name" => "Felivaru", "name_dhivehi" => "ފެލިވަރު"],
            ["name" => "Kanuhuraa", "name_dhivehi" => "ކަނުހުރާ"],
            ["name" => "Komandoo", "name_dhivehi" => "ކޮމަންޑޫ"],
            ["name" => "Kuredhdhoo", "name_dhivehi" => "ކުރެއްދޫ"],
            ["name" => "Madhiriguraidhoo", "name_dhivehi" => "މަދިރިގުރައިދޫ"],
            ["name" => "Alhigaa", "name_dhivehi" => "އަޅިގާ"],
            ["name" => "Bodufinolhu", "name_dhivehi" => "ބޮޑުފިނޮޅު"],
            ["name" => "Bovalhafushi", "name_dhivehi" => "ބޮވަޅަފުށި"],
            ["name" => "Dhashugirifinolhu", "name_dhivehi" => "ދަށުގިރިފިނޮޅު"],
            ["name" => "Dheruhfinolhu", "name_dhivehi" => "ދެރުއްފިނޮޅު"],
            ["name" => "Dhidhdhoo", "name_dhivehi" => "ދިއްދޫ"],
            ["name" => "Dhirunbaafushi", "name_dhivehi" => "ދިރުނބާފުށި"],
            ["name" => "Faadhoo", "name_dhivehi" => "ފާދޫ"],
            ["name" => "Fainuaadhamhuraa", "name_dhivehi" => "ފައިނުއާދަމްހުރާ"],
            ["name" => "Farufinolhu", "name_dhivehi" => "ފަރުފިނޮޅު"],
            ["name" => "Fehigili", "name_dhivehi" => "ފެހިގިލި"],
            ["name" => "Fushifaru", "name_dhivehi" => "ފުށިފަރު"],
            ["name" => "Gaaerifaru", "name_dhivehi" => "ގާއެރިފަރު"],
            ["name" => "Govaafushi", "name_dhivehi" => "ގޮވާފުށީ"],
            ["name" => "Hudhufushi", "name_dhivehi" => "ހުދުފުށި"],
            ["name" => "Huruvalhi", "name_dhivehi" => "ހަރުވަޅި"],
            ["name" => "Innahuraa", "name_dhivehi" => "އިންނަހުރާ"],
            ["name" => "Kalhumanjehuraa", "name_dhivehi" => "ކަޅުމަންޖެހުރާ"],
            ["name" => "Kanifushi", "name_dhivehi" => "ކަނިފުށި"],
            ["name" => "Lhohi", "name_dhivehi" => "ޅޮހި"],
            ["name" => "Lhosalafushi", "name_dhivehi" => "ޅޮސަލަފުށި"],
            ["name" => "Maakoa", "name_dhivehi" => "މާކޮއެ"],
            ["name" => "Maavaafushi", "name_dhivehi" => "މާވާފުށި"],
            ["name" => "Maabinhuraa", "name_dhivehi" => "މާބިންހުރާ"],
            ["name" => "Madivaru", "name_dhivehi" => "މަޑިވަރު"],
            ["name" => "Maduvvari", "name_dhivehi" => "މަޑުއްވަރީ"],
            ["name" => "Maidhoo", "name_dhivehi" => "މައިދޫ"],
            ["name" => "Medhaadihuraa", "name_dhivehi" => "މެދާޑިހުރާ"],
            ["name" => "Medhafushi", "name_dhivehi" => "މެދަފުށި"],
            ["name" => "Meedhaahuraa", "name_dhivehi" => "މީދާހުރާ"],
            ["name" => "Meyafushi", "name_dhivehi" => "މެޔަފުށި"],
            ["name" => "Ookolhufinolhu", "name_dhivehi" => "އޫކޮޅުފިނޮޅު"],
            ["name" => "Ruhelhifushi", "name_dhivehi" => "ރުހެޅިފުށި"],
            ["name" => "Thilamaafushi", "name_dhivehi" => "ތިލަމާފުށި"],
            ["name" => "Uthuruhuraa", "name_dhivehi" => "އުތުރުހުރާ"],
            ["name" => "Varihuraa", "name_dhivehi" => "ވަރިހުރާ"],
            ["name" => "Vavvaru", "name_dhivehi" => "ވަށްވަރު"],
            ["name" => "Vejvah", "name_dhivehi" => "ވެޖްވަށް"],
            ["name" => "Veligandu", "name_dhivehi" => "ވެލިގަނޑު"],
            ["name" => "Vihafaru", "name_dhivehi" => "ވިހަފަރު"],
            ["name" => "Male", "name_dhivehi" => "މާލެ"],
            ["name" => "Villingili", "name_dhivehi" => "ވިލިނގިލި"],
            ["name" => "Hulhumale", "name_dhivehi" => "ހުޅުމާލެ"],
            ["name" => "Kaashidhoo", "name_dhivehi" => "ކާށިދޫ"],
            ["name" => "Gaafaru", "name_dhivehi" => "ގާފަރު"],
            ["name" => "Dhiffushi", "name_dhivehi" => "ދިއްފުށި"],
            ["name" => "Thulusdhoo", "name_dhivehi" => "ތުލުސްދޫ"],
            ["name" => "Huraa", "name_dhivehi" => "ހުރާ"],
            ["name" => "Himmafushi", "name_dhivehi" => "ހިންމަފުށި"],
            ["name" => "Gulhi", "name_dhivehi" => "ގުޅި"],
            ["name" => "Maafushi", "name_dhivehi" => "މާފުށި"],
            ["name" => "Guraidhoo", "name_dhivehi" => "ގުރައިދޫ"],
            ["name" => "Hulhule", "name_dhivehi" => "ހުޅުލެ"],
            ["name" => "Thilafushi", "name_dhivehi" => "ތިލަފުށި"],
            ["name" => "Kuda Bandos", "name_dhivehi" => "ކުޑަބަނޑޮސް"],
            ["name" => "Kanduoiygiri", "name_dhivehi" => "ކަނޑުއޮތްގިރި"],
            ["name" => "Aarah", "name_dhivehi" => "އާރަށް"],
            ["name" => "Dhoonidhoo", "name_dhivehi" => "ދޫނިދޫ"],
            ["name" => "Funadhoo", "name_dhivehi" => "ފުނަދޫ"],
            ["name" => "Girifushi", "name_dhivehi" => "ގިރިފުށި"],
            ["name" => "Gaamaadhoo", "name_dhivehi" => "ގާމާދޫ"],
            ["name" => "Feydhoofinolhu", "name_dhivehi" => "ފޭދޫފިނޮޅު"],
            ["name" => "Asdhu", "name_dhivehi" => "އަސްދޫ"],
            ["name" => "Bandos", "name_dhivehi" => "ބަނޑޮސް"],
            ["name" => "Baros", "name_dhivehi" => "ބަރޮސް"],
            ["name" => "Biyaadhu", "name_dhivehi" => "ބިޔާދޫ"],
            ["name" => "Boduhithi", "name_dhivehi" => "ބޮޑުހިތި"],
            ["name" => "Bolifushi", "name_dhivehi" => "ބޮލިފުށި"],
            ["name" => "Farukolhufushi", "name_dhivehi" => "ފަރުކޮޅުފުށި"],
            ["name" => "Rannalhi", "name_dhivehi" => "ރަންނާޅި"],
            ["name" => "Makunufushi", "name_dhivehi" => "މަކުނުފުށި"],
            ["name" => "Dhigufinohlu", "name_dhivehi" => "ދިގުފިނޮޅު"],
            ["name" => "Emboodhu", "name_dhivehi" => "އެނބޫދޫ"],
            ["name" => "Eriyadhoo", "name_dhivehi" => "އެރިޔަދޫ"],
            ["name" => "Fihaalhohi", "name_dhivehi" => "ފިހާޅޮހި"],
            ["name" => "Kuda Huraa", "name_dhivehi" => "ކުޑަހުރާ"],
            ["name" => "Furanafushi", "name_dhivehi" => "ފުރަނަފުށި"],
            ["name" => "Bodufinolhu", "name_dhivehi" => "ބޮޑުފިނޮޅު"],
            ["name" => "Gasfinolhu", "name_dhivehi" => "ގަސްފިނޮޅު"],
            ["name" => "Giraavaru", "name_dhivehi" => "ގިރާވަރު"],
            ["name" => "Helegeli", "name_dhivehi" => "ހެލެނގެލި"],
            ["name" => "Lankanfushi", "name_dhivehi" => "ލަންކަންފުށި"],
            ["name" => "Ihuru", "name_dhivehi" => "އިހުރު"],
            ["name" => "Kandoomafushi", "name_dhivehi" => "ކަނޑޫމާފުށި"],
            ["name" => "Kanifinolhu", "name_dhivehi" => "ކަނިފިނޮޅު"],
            ["name" => "Kudahithi", "name_dhivehi" => "ކުޑަހިތި"],
            ["name" => "Vihamanaafushi", "name_dhivehi" => "ވިހަމަނާފުށި"],
            ["name" => "Velassaru", "name_dhivehi" => "ވެލަސަރު"],
            ["name" => "Lhohifushi", "name_dhivehi" => "ޅޮހިފުށި"],
            ["name" => "Mankunudhoo", "name_dhivehi" => "މަކުނުދޫ"],
            ["name" => "Meerufenfushi", "name_dhivehi" => "މީރުފެންފުށި"],
            ["name" => "Nakatchafushi", "name_dhivehi" => "ނަކައްޗާފުށި"],
            ["name" => "Olhuveli", "name_dhivehi" => "އޮޅުވެލި"],
            ["name" => "Veligandu Huraa", "name_dhivehi" => "ވެލިގަނޑުހުރާ"],
            ["name" => "Lankanfinolhu", "name_dhivehi" => "ލަންކަންފިނޮޅު"],
            ["name" => "Medhufinolhu", "name_dhivehi" => "މެދުފިނޮޅު"],
            ["name" => "Mahaanaelhi Huraa", "name_dhivehi" => "މަހާނައެޅިހުރާ"],
            ["name" => "Ziyaaraiyfushi", "name_dhivehi" => "ޒިޔާރަތްފުށި"],
            ["name" => "Kanuoiy Huraa", "name_dhivehi" => "ކަނުއޮތްހުރާ"],
            ["name" => "Thulhagiri", "name_dhivehi" => "ތުޅާގިރި"],
            ["name" => "Hambadhu", "name_dhivehi" => "ހަނބަދޫ"],
            ["name" => "Embudhu Finolhu", "name_dhivehi" => "އެނބޫދޫ ފިނޮޅު"],
            ["name" => "Vaadhu", "name_dhivehi" => "ވާދޫ"],
            ["name" => "Vabbinfaru", "name_dhivehi" => "ވަށްބިންފަރު"],
            ["name" => "Vilivaru", "name_dhivehi" => "ވިލިވަރު"],
            ["name" => "Bodu Huraa", "name_dhivehi" => "ބޮޑުހުރާ"],
            ["name" => "Bushy", "name_dhivehi" => "ބުށީ"],
            ["name" => "Emboodhoo Finolhu", "name_dhivehi" => "އެނބޫދޫފިނޮޅު"],
            ["name" => "Erruhhuraa", "name_dhivehi" => "އެއްރުއްހުރާ"],
            ["name" => "Farukolhufushi", "name_dhivehi" => "ފަރުކޮޅުފުށި"],
            ["name" => "Feydhoo", "name_dhivehi" => "ފޭދޫ"],
            ["name" => "Hembadhoo", "name_dhivehi" => "ހެނބަދޫ"],
            ["name" => "Kaduoiygiri", "name_dhivehi" => "ކަނޑުއޮތްގިރި"],
            ["name" => "Kagi", "name_dhivehi" => "ކަގި"],
            ["name" => "Kudafinolhu", "name_dhivehi" => "ކުޑަފިނޮޅު"],
            ["name" => "Little Huraa", "name_dhivehi" => "ލިޓްލް ހުރާ"],
            ["name" => "Maadhoo", "name_dhivehi" => "މާދޫ"],
            ["name" => "Madivaru", "name_dhivehi" => "މަޑިވަރު"],
            ["name" => "Maniyafushi", "name_dhivehi" => "މަނިޔަފުށި"],
            ["name" => "Masleggihuraa", "name_dhivehi" => "މަސްލެއްގިހުރާ"],
            ["name" => "Oidhunifinolhu", "name_dhivehi" => "އޮތްދުނިފިނޮޅު"],
            ["name" => "Olhigandufinolhu", "name_dhivehi" => "އޮޅިގަނޑުފިނޮޅު"],
            ["name" => "Olhuhali", "name_dhivehi" => "އޮޅުހަލި"],
            ["name" => "Rasfari", "name_dhivehi" => "ރަސްފަރި"],
            ["name" => "Thaburudhoo", "name_dhivehi" => "ތަނބުރުދޫ"],
            ["name" => "Tholhimaraahuraa", "name_dhivehi" => "ތޮޅިމަރާހުރާ"],
            ["name" => "Thulusdhoo Irumathee hura", "name_dhivehi" => "ތުލުސްދޫ އިރުމަތީ ހުރާ"],
            ["name" => "Vaagali", "name_dhivehi" => "ވާގަލި"],
            ["name" => "Vabboahuraa", "name_dhivehi" => "ވަށްބޯހުރާ"],
            ["name" => "Valassaru", "name_dhivehi" => "ވަލައްސަރު"],
            ["name" => "Vammaafushi", "name_dhivehi" => "ވަށްމާފުށި"],
            ["name" => "Villingilimathidhahuraa", "name_dhivehi" => "ވިލިނގިލިމަތިދަހުރާ"],
            ["name" => "Thoddoo", "name_dhivehi" => "ތޮއްޑޫ"],
            ["name" => "Rasdhoo", "name_dhivehi" => "ރަސްދޫ"],
            ["name" => "Ukulhas", "name_dhivehi" => "އުކުޅަސް"],
            ["name" => "Mathiveri", "name_dhivehi" => "މަތިވެރި"],
            ["name" => "Bodufolhudhoo", "name_dhivehi" => "ބޮޑުފޮޅުދޫ"],
            ["name" => "Feridhoo", "name_dhivehi" => "ފެރިދޫ"],
            ["name" => "Maalhos", "name_dhivehi" => "މާޅޮސް"],
            ["name" => "Himandhoo", "name_dhivehi" => "ހިމަންދޫ"],
            ["name" => "Bathala", "name_dhivehi" => "ބަތަލާ"],
            ["name" => "Ellaidhu", "name_dhivehi" => "އެއްލައިދޫ"],
            ["name" => "Fesdhoo", "name_dhivehi" => "ފެސްދޫ"],
            ["name" => "Gangehi", "name_dhivehi" => "ގަންގެހި"],
            ["name" => "Halaveli", "name_dhivehi" => "ހަލަވެލި"],
            ["name" => "Kuramathi", "name_dhivehi" => "ކުރަމަތި"],
            ["name" => "Maayaafushi", "name_dhivehi" => "މާޔާފުށި"],
            ["name" => "Madoogali", "name_dhivehi" => "މަޑޫގަލި"],
            ["name" => "Kudafolhudhoo", "name_dhivehi" => "ކުޑަފޮޅުދޫ"],
            ["name" => "Veligandu", "name_dhivehi" => "ވެލިގަނޑު"],
            ["name" => "Velidhoo", "name_dhivehi" => "ވެލިދޫ"],
            ["name" => "Mushimasmigili", "name_dhivehi" => "މުށިމަސްގިލި"],
            ["name" => "Avi Island", "name_dhivehi" => "އަވި އައިލެންޑް"],
            ["name" => "Machchafushi", "name_dhivehi" => "މައްޗަފުށި"],
            ["name" => "Alikoirah", "name_dhivehi" => "އަލިކޮއިރަށް"],
            ["name" => "Beyrumadivaru", "name_dhivehi" => "ބޭރުމަޑިވަރު"],
            ["name" => "Dhinnolhufinolhu", "name_dhivehi" => "ދިއްނޮޅުފިނޮޅު"],

        ];
        // 
        Model::unguard();
        $atolls = array(
            array('id' => 1, 'english_name' => 'North Thiladhunmathi', 'english_code' => 'HA'),
            array('id' => 2, 'english_name' => 'South Thiladhunmathi', 'english_code' => 'HDh'),
            array('id' => 3, 'english_name' => 'North Miladhunmadulu', 'english_code' => 'Sh'),
            array('id' => 4, 'english_name' => 'South Miladhunmadulu', 'english_code' => 'N'),
            array('id' => 5, 'english_name' => 'North Maalhosmadulu', 'english_code' => 'R'),
            array('id' => 6, 'english_name' => 'South Maalhosmadulu', 'english_code' => 'B'),
            array('id' => 7, 'english_name' => 'Faadhippolhu', 'english_code' => 'Lh'),
            array('id' => 8, 'english_name' => 'Male\'', 'english_code' => 'K'),
            array('id' => 9, 'english_name' => 'North Ari Atoll', 'english_code' => 'AA'),
            array('id' => 10, 'english_name' => 'South Ari Atoll', 'english_code' => 'ADh'),
            array('id' => 11, 'english_name' => 'Felidhu Atoll', 'english_code' => 'V'),
            array('id' => 12, 'english_name' => 'Mulakatholhu', 'english_code' => 'M'),
            array('id' => 13, 'english_name' => 'North Nilandhe Atoll', 'english_code' => 'F'),
            array('id' => 14, 'english_name' => 'South Nilandhe Atoll', 'english_code' => 'Dh'),
            array('id' => 15, 'english_name' => 'Kolhumadulu', 'english_code' => 'Th'),
            array('id' => 16, 'english_name' => 'Hadhdhunmathi', 'english_code' => 'L'),
            array('id' => 17, 'english_name' => 'North Huvadhu Atoll', 'english_code' => 'GA'),
            array('id' => 18, 'english_name' => 'South Huvadhu Atoll', 'english_code' => 'GDh'),
            array('id' => 19, 'english_name' => 'Fuvahmulah', 'english_code' => 'Gn'),
            array('id' => 20, 'english_name' => 'Addu City', 'english_code' => 'S'),
        );
        $datetime = new Carbon;
        $modifiedAtolls= array_map(function($item) use ($datetime) {
            $item['created_at'] = $datetime;
            $item['updated_at'] = $datetime;
            return $item;
        }, $atolls);

        Atoll::insert($modifiedAtolls);

        $islands = array(
            /**
             * 1. Ha atoll islands
             */
            array("id" => 1, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.996464, "longitude" => 7.016098, "name" => "Molhadhoo"),
            array("id" => 2, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.984406, "longitude" => 6.852400, "name" => "Maarandhoo"),
            array("id" => 3, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.896653, "longitude" => 6.981879, "name" => "Hoarafushi"),
            array("id" => 4, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.215460, "longitude" => 6.918450, "name" => "Kelaa"),
            array("id" => 5, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.213152, "longitude" => 6.169160, "name" => "Baarah"),
            array("id" => 6, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.926103, "longitude" => 6.953145, "name" => "Ihavandhoo"),
            array("id" => 7, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.114046, "longitude" => 6.887120, "name" => "Dhidhdhoo"),
            array("id" => 8, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.995584, "longitude" => 6.844469, "name" => "Thakandhoo"),
            array("id" => 9, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.164148, "longitude" => 6.898663, "name" => "Vashafaru"),
            array("id" => 10, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.167143, "longitude" => 6.837774, "name" => "Muraidhoo"),
            array("id" => 11, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.898976, "longitude" => 7.103806, "name" => "Thuraakunu"),
            array("id" => 12, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.112270, "longitude" => 6.8350270, "name" => "Utheemu"),
            array("id" => 13, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 73.235269, "longitude" => 6.897072, "name" => "Filladhoo"),
            array("id" => 14, "atoll_id" => 1, "atoll_code" => "HA", "latitude" => 72.925094, "longitude" => 7.083835, "name" => "Uligan"),

            /**
             * 2. HDh atoll islands
             */
            array("id" => 15, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.024126, "longitude" => 6.724919, "name" => "Hirimaradhoo"),
            array("id" => 16, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.027382, "longitude" => 6.658286, "name" => "Kunburudhoo"),
            array("id" => 17, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 72.979807, "longitude" => 6.542908, "name" => "Neykurendhoo"),
            array("id" => 18, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.069457, "longitude" => 6.623269, "name" => "Kulhudhuffushi"),
            array("id" => 19, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 72.946828, "longitude" => 6.714940, "name" => "Nellaidhoo"),
            array("id" => 20, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.051639, "longitude" => 6.571084, "name" => "Kumundhoo"),
            array("id" => 21, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 72.705201, "longitude" => 6.409141, "name" => "Makunudhoo"),
            array("id" => 22, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.082409, "longitude" => 6.662525, "name" => "Nolhivaran"),
            array("id" => 23, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.120619, "longitude" => 6.693313, "name" => "Nolhivaranfaru"),
            array("id" => 24, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 72.934249, "longitude" => 6.747121, "name" => "Naivaadhoo"),
            array("id" => 25, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.177794, "longitude" => 6.766965, "name" => "Hanimaadhoo"),
            array("id" => 26, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 72.952869, "longitude" => 6.549727, "name" => "Vaikaradhoo"),
            array("id" => 27, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.053782, "longitude" => 6.515374, "name" => "Maavaidhoo"),
            array("id" => 28, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.053905, "longitude" => 6.784964, "name" => "Faridhoo"),
            array("id" => 29, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 72.996598, "longitude" => 6.665513, "name" => "Kurinbi"),
            array("id" => 30, "atoll_id" => 2, "atoll_code" => "HDh", "latitidue" => 73.053514, "longitude" => 6.746074, "name" => "Finey"),

            /**
             * 3. Sh atoll islands
             */

            array("id" => 31, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.048712, "longitude" => 6.360313, "name" => "Feydhoo"),
            array("id" => 32, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.245671, "longitude" => 6.287913, "name" => "Milandhoo"),
            array("id" => 33, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.290725, "longitude" => 6.150369, "name" => "Funadhoo"),
            array("id" => 34, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.054520, "longitude" => 6.054858, "name" => "Komandoo"),
            array("id" => 35, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 72.973835, "longitude" => 6.338018, "name" => "Bilehfahi"),
            array("id" => 36, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.251372, "longitude" => 6.168837, "name" => "Lhaimagu"),
            array("id" => 37, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 72.915696, "longitude" => 6.440665, "name" => "Kanditheemu"),
            array("id" => 38, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.209658, "longitude" => 6.348893, "name" => "Feevah"),
            array("id" => 39, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.218099, "longitude" => 6.264328, "name" => "Narudhoo"),
            array("id" => 40, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.283869, "longitude" => 6.073091, "name" => "Maaungoodhoo"),
            array("id" => 41, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.149293, "longitude" => 6.326729, "name" => "Foakaidhoo"),
            array("id" => 42, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.069023, "longitude" => 6.434146, "name" => "Noomaraa"),
            array("id" => 43, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 73.061094, "longitude" => 6.209848, "name" => "Maroshi"),
            array("id" => 44, "atoll_id" => 3, "atoll_code" => "Sh", "latitude" => 72.929577, "longitude" => 6.430076, "name" => "Goidhoo"),

            /**
             * 4. N atoll islands
             */
            array("id" => 45, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.274239, "longitude" => 5.663899, "name" => "Velidhoo"),
            array("id" => 46, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.476542, "longitude" => 5.824048, "name" => "Maafaru"),
            array("id" => 47, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.215791, "longitude" => 5.743517, "name" => "Fodhdhoo"),
            array("id" => 48, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.362318, "longitude" => 5.790502, "name" => "Miladhoo"),
            array("id" => 49, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.262794, "longitude" => 5.754955, "name" => "Holhudhoo"),
            array("id" => 50, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.392908, "longitude" => 5.967417, "name" => "Henbadhoo"),
            array("id" => 51, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.362182, "longitude" => 5.776299, "name" => "Magoodhoo"),
            array("id" => 52, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.415200, "longitude" => 5.952303, "name" => "Kendhikulhudhoo"),
            array("id" => 53, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.456039, "longitude" => 5.902501, "name" => "Maalhendhoo"),
            array("id" => 54, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.466435, "longitude" => 5.881740, "name" => "Landhoo"),
            array("id" => 55, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.410972, "longitude" => 5.766205, "name" => "Manadhoo"),
            array("id" => 56, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.377399, "longitude" => 5.815795, "name" => "Lhohi"),
            array("id" => 57, "atoll_id" => 4, "atoll_code" => "N", "latitude" => 73.400451, "longitude" => 5.882637, "name" => "Kudafari"),

            /**
             * 5. R atoll islands
             */
            array("id" => 58, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.036303, "longitude" => 5.476875, "name" => "Inguraidhoo"), 
            array("id" => 59, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 72.855096, "longitude" => 5.618734, "name" => "Kandholhudhoo"), 
            array("id" => 60, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 72.991073, "longitude" => 5.855380, "name" => "Vaadhoo"), 
            array("id" => 61, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 72.896006, "longitude" => 5.486265, "name" => "Maduvvari"), 
            array("id" => 62, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.030504, "longitude" => 5.448406, "name" => "Kinolhas"), 
            array("id" => 63, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.034446, "longitude" => 5.463281, "name" => "Fainu"), 
            array("id" => 64, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.043154, "longitude" => 5.606037, "name" => "Maakurathu"), 
            array("id" => 65, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.006620, "longitude" => 5.792765, "name" => "Angolhitheemu"), 
            array("id" => 66, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.012617, "longitude" => 5.766033, "name" => "Hulhudhuffaaru"), 
            array("id" => 67, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.030155, "longitude" => 5.668157, "name" => "Ungoofaaru"), 
            array("id" => 68, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 72.953034, "longitude" => 5.967254, "name" => "Alifushi"), 
            array("id" => 69, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.003198, "longitude" => 5.807783, "name" => "Rasgetheemu"), 
            array("id" => 70, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.043478, "longitude" => 5.562959, "name" => "Rasmaadhoo"), 
            array("id" => 71, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 72.955283, "longitude" => 5.458021, "name" => "Meedhoo"), 
            array("id" => 72, "atoll_id" => 5, "atoll_code" => "R", "latitude" => 73.043800, "longitude" => 5.549437, "name" => "Innamaadhoo"), 

            /**
             * 6. B atoll islands
             */
            array("id" => 73, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.010150, "longitude" => 5.275378, "name" => "Kendhoo"), 
            array("id" => 74, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 72.839980, "longitude" => 5.022891, "name" => "Thulhaadhoo"), 
            array("id" => 75, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 72.933336, "longitude" => 4.885731, "name" => "Fulhadhoo"), 
            array("id" => 76, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.130170, "longitude" => 5.157685, "name" => "Dharavandhoo"), 
            array("id" => 77, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 72.967133, "longitude" => 4.882001, "name" => "Fehendhoo"), 
            array("id" => 78, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.000051, "longitude" => 4.870928, "name" => "Goidhoo"), 
            array("id" => 79, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.108144, "longitude" => 5.134814, "name" => "Maalhos"), 
            array("id" => 80, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.123047, "longitude" => 5.187738, "name" => "Dhonfan"), 
            array("id" => 81, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 72.922791, "longitude" => 5.007428, "name" => "Hithaadhoo"), 
            array("id" => 82, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.137016, "longitude" => 5.281926, "name" => "Kamadhoo"), 
            array("id" => 83, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.070395, "longitude" => 5.103483, "name" => "Eydhafushi"), 
            array("id" => 84, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.070785, "longitude" => 5.300333, "name" => "Kudarikilu"), 
            array("id" => 85, "atoll_id" => 6, "atoll_code" => "B", "latitude" => 73.125177, "longitude" => 5.215138, "name" => "Kihaadhoo"), 

            /**
             * 7. Lh atoll islands
             */
            array("id" => 86, "atoll_id" => 7, "atoll_code" => "Lh", "latitude" => 73.463614, "longitude" => 5.333784, "name" => "Kurendhoo"),
            array("id" => 87, "atoll_id" => 7, "atoll_code" => "Lh", "latitude" => 73.606382, "longitude" => 5.278309, "name" => "Olhuvelifushi"),
            array("id" => 88, "atoll_id" => 7, "atoll_code" => "Lh", "latitude" => 73.412152, "longitude" => 5.491961, "name" => "Hinnavaru"),
            array("id" => 89, "atoll_id" => 7, "atoll_code" => "Lh", "latitude" => 73.365165, "longitude" => 5.445225, "name" => "Naifaru"),
            array("id" => 200, "atoll_id" => 7, "atoll_code" => "Lh", "latitude" => 73.415272, "longitude" => 5.362965, "name" => "Maafilaafushi"),

            /**
             * 8. K atoll islands
             */
            array("id" => 90, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.713752, "longitude" => 4.442153, "name" => "Dhiffushi"),
            array("id" => 91, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.600693, "longitude" => 4.334328, "name" => "Huraa"),
            array("id" => 92, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.571863, "longitude" => 4.308904, "name" => "Hinmafushi"),
            array("id" => 93, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.509114, "longitude" => 3.990986, "name" => "Gulhi"),
            array("id" => 94, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.499846, "longitude" => 4.736115, "name" => "Gaafaru"),
            array("id" => 95, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.650439, "longitude" => 4.374358, "name" => "Thulusdhoo"),
            array("id" => 96, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.468191, "longitude" => 3.900871, "name" => "Guraidhoo"),
            array("id" => 97, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.459609, "longitude" => 4.956995, "name" => "Kaashidhoo"),
            array("id" => 98, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.509878, "longitude" => 4.175030, "name" => "Male'"),
            array("id" => 99, "atoll_id" => 8, "atoll_code" => "K", "latitude" => 73.489391, "longitude" => 3.941452, "name" => "Maafushi"),

            /**
             * 9. AA atoll islands
             */
            array("id" => 101, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.863734, "longitude" => 4.214655, "name" => "Ukulhas"),
            array("id" => 102, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.744502, "longitude" => 3.921612, "name" => "Himandhoo"),
            array("id" => 103, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.991977, "longitude" => 4.263105, "name" => "Rasdhoo"),
            array("id" => 104, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.773479, "longitude" => 4.185455, "name" => "Bodufolhudhoo"),
            array("id" => 105, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.719628, "longitude" => 3.986480, "name" => "Maalhos"),
            array("id" => 106, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.945631, "longitude" => 4.437322, "name" => "Thoddoo"),
            array("id" => 107, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.725161, "longitude" => 4.051082, "name" => "Feridhoo"),
            array("id" => 108, "atoll_id" => 9, "atoll_code" => "AA", "latitude" => 72.745802, "longitude" => 4.191563, "name" => "Mathiveri"),
            /**
             * 10. ADh atoll islands
             */
            array("id" => 109, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.955405, "longitude" => 3.606805, "name" => "Dhangethi"),
            array("id" => 110, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.924100, "longitude" => 3.526920, "name" => "Dhigurah"),
            array("id" => 111, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.923693, "longitude" => 3.775587, "name" => "Kunburudhoo"),
            array("id" => 112, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.782910, "longitude" => 3.489213, "name" => "Fenfushi"),
            array("id" => 113, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.836916, "longitude" => 3.476670, "name" => "Maamigili"),
            array("id" => 114, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.710082, "longitude" => 3.697902, "name" => "Mandhoo"),
            array("id" => 115, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.955390, "longitude" => 3.849337, "name" => "Hangnaameedhoo"),
            array("id" => 116, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.969066, "longitude" => 3.757220, "name" => "Mahibadhoo"),
            array("id" => 117, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.961131, "longitude" => 3.791600, "name" => "Omadhoo"),
            array("id" => 118, "atoll_id" => 10, "atoll_code" => "ADh", "latitude" => 72.879502, "longitude" => 3.484906, "name" => "Dhidhdhoo"),
            /*
             * 11. V atoll islands
             */
            array("id" => 119, "atoll_id" => 11, "atoll_code" => "V", "latitude" => 73.537856, "longitude" => 3.487673, "name" => "Thinadhoo"),
            array("id" => 120, "atoll_id" => 11, "atoll_code" => "V", "latitude" => 73.469823, "longitude" => 3.314940, "name" => "Rakeedhoo"),
            array("id" => 121, "atoll_id" => 11, "atoll_code" => "V", "latitude" => 73.550110, "longitude" => 3.462117, "name" => "Keyodhoo"),
            array("id" => 122, "atoll_id" => 11, "atoll_code" => "V", "latitude" => 73.415786, "longitude" => 3.680477, "name" => "Fulidhoo"),
            array("id" => 123, "atoll_id" => 11, "atoll_code" => "V", "latitude" => 73.547044, "longitude" => 3.471751, "name" => "Felidhoo"),
            /**
             * 12. M atoll islands
             */
            array("id" => 124, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.565258, "longitude" => 3.112102, "name" => "Dhiggaru"),
            array("id" => 125, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.581365, "longitude" => 2.918991, "name" => "Muli"),
            array("id" => 126, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.572897, "longitude" => 3.104647, "name" => "Maduvvari"),
            array("id" => 127, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.599765, "longitude" => 2.955840, "name" => "Veyvah"),
            array("id" => 128, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.584256, "longitude" => 2.946387, "name" => "Mulah"),
            array("id" => 129, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.424440, "longitude" => 2.780810, "name" => "Kolhufushi"),
            array("id" => 130, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.639095, "longitude" => 3.089010, "name" => "Raiymandhoo"),
            array("id" => 131, "atoll_id" => 12, "atoll_code" => "M", "latitude" => 73.577401, "longitude" => 2.895659, "name" => "Naalaafushi"),
            /**
             * 13. F atoll islands
             */
            array("id" => 132, "atoll_id" => 13, "atoll_code" => "F", "latitude" => 72.925489, "longitude" => 3.063024, "name" => "Nilandhoo"),
            array("id" => 133, "atoll_id" => 13, "atoll_code" => "F", "latitude" => 72.984090, "longitude" => 3.118307, "name" => "Bilehdhoo"),
            array("id" => 134, "atoll_id" => 13, "atoll_code" => "F", "latitude" => 72.963386, "longitude" => 3.078585, "name" => "Dharanboodhoo"),
            array("id" => 135, "atoll_id" => 13, "atoll_code" => "F", "latitude" => 73.002170, "longitude" => 3.269859, "name" => "Feeali"),
            array("id" => 136, "atoll_id" => 13, "atoll_code" => "F", "latitude" => 72.984090, "longitude" => 3.118307, "name" => "Magoodhoo"),
            /**
             * 14. Dh atoll islands
             */
            array("id" => 137, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 72.893716, "longitude" => 2.671707, "name" => "Kudahuvadhoo"),
            array("id" => 138, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 73.006371, "longitude" => 2.998282, "name" => "Meedhoo"),
            array("id" => 139, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 72.846363, "longitude" => 2.858436, "name" => "Hulhudheli"),
            array("id" => 140, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 72.895893, "longitude" => 2.925640, "name" => "Rinbudhoo"),
            array("id" => 141, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 72.991113, "longitude" => 2.936944, "name" => "Bandidhoo"),
            array("id" => 142, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 73.026270, "longitude" => 2.803711, "name" => "Gemendhoo"),
            array("id" => 143, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 72.963335, "longitude" => 2.695566, "name" => "Maaenboodhoo"),
            array("id" => 144, "atoll_id" => 14, "atoll_code" => "Dh", "latitude" => 73.003220, "longitude" => 2.725110, "name" => "Vaani"),
            /**
             * 15. Th atoll islands
             */
            array("id" => 145, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.354817, "longitude" => 2.356963, "name" => "Madifushi"),
            array("id" => 146, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.336931, "longitude" => 2.340187, "name" => "Dhiyamigili"),
            array("id" => 147, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.308229, "longitude" => 2.502818, "name" => "Vilufushi"),
            array("id" => 148, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.212400, "longitude" => 2.253139, "name" => "Gaadhiffushi"),
            array("id" => 149, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.094457, "longitude" => 2.186917, "name" => "Veymandoo"),
            array("id" => 150, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.142935, "longitude" => 2.205529, "name" => "Thimarafushi"),
            array("id" => 151, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.105995, "longitude" => 2.558714, "name" => "Buruni"),
            array("id" => 152, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 72.932530, "longitude" => 2.269611, "name" => "Hirilandhoo"),
            array("id" => 153, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.319421, "longitude" => 2.324968, "name" => "Guraidhoo"),
            array("id" => 154, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.023549, "longitude" => 2.167358, "name" => "Omadhoo"),
            array("id" => 155, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 72.916608, "longitude" => 2.321204, "name" => "Kandoodhoo"),
            array("id" => 156, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 73.066000, "longitude" => 2.168105, "name" => "Kinbidhoo"),
            array("id" => 157, "atoll_id" => 15, "atoll_code" => "Th", "latitude" => 72.941997, "longitude" => 2.291691, "name" => "Vandhoo"),
            /**
             * 16. L atoll islands
             */
            array("id" => 158, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.389866, "longitude" => 1.818038, "name" => "Maamendhoo"),
            array("id" => 159, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.388047, "longitude" => 1.795657, "name" => "Hithadhoo"),
            array("id" => 160, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.452090, "longitude" => 1.821457, "name" => "Gaadhoo"),
            array("id" => 161, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.504239, "longitude" => 1.836324, "name" => "Fonadhoo"),
            array("id" => 162, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.533739, "longitude" => 2.011052, "name" => "Mundoo"),
            array("id" => 163, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.242347, "longitude" => 1.885328, "name" => "Maavah"),
            array("id" => 164, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.368361, "longitude" => 1.783307, "name" => "Kunahandhoo"),
            array("id" => 165, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.532199, "longitude" => 2.030136, "name" => "Maabaidhoo"),
            array("id" => 166, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.568444, "longitude" => 2.119007, "name" => "Isdhoo"),
            array("id" => 167, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.539758, "longitude" => 1.911136, "name" => "Gan"),
            array("id" => 168, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.537528, "longitude" => 1.988794, "name" => "Kalhaidhoo"),
            array("id" => 169, "atoll_id" => 16, "atoll_code" => "L", "latitude" => 73.544340, "longitude" => 2.093724, "name" => "Dhanbidhoo"),
            /**
             * 17. GA atoll islands
             */
            array("id" => 170, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.462094, "longitude" => 0.621114, "name" => "Dhaandhoo"),
            array("id" => 171, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.539993, "longitude" => 0.351344, "name" => "Kanduhulhudhoo"),
            array("id" => 172, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.558971, "longitude" => 0.476468, "name" => "Dhiyadhoo"),
            array("id" => 173, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.446208, "longitude" => 0.636416, "name" => "Nilandhoo"),
            array("id" => 174, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.568521, "longitude" => 0.442017, "name" => "Gemanafushi"),
            array("id" => 175, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.549653, "longitude" => 0.499554, "name" => "Kondey"),
            array("id" => 176, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.185015, "longitude" => 0.837154, "name" => "Kolamaafushi"),
            array("id" => 177, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.242237, "longitude" => 0.556858, "name" => "Dhevvadhoo"),
            array("id" => 178, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.434885, "longitude" => 0.755293, "name" => "Vilingili"),
            array("id" => 179, "atoll_id" => 17, "atoll_code" => "GA", "latitude" => 73.438891, "longitude" => 0.713464, "name" => "Maamendhoo"),
            /**
             * 18. GDh atoll islands
             */
            array("id" => 180, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.104873, "longitude" => 0.253248, "name" => "Rathafandhoo"),
            array("id" => 181, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.040729, "longitude" => 0.293590, "name" => "Nadellaa"),
            array("id" => 182, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.456435, "longitude" => 0.289472, "name" => "Gadhdhoo"),
            array("id" => 183, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 72.999236, "longitude" => 0.459010, "name" => "Madaveli"),
            array("id" => 184, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 72.997227, "longitude" => 0.530185, "name" => "Thinadhoo"),
            array("id" => 185, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.273878, "longitude" => 0.227282, "name" => "Vaadhoo"),
            array("id" => 186, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.189809, "longitude" => 0.199020, "name" => "Faresmaathodaa"),
            array("id" => 187, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.003249, "longitude" => 0.444125, "name" => "Hoandedhdhoo"),
            array("id" => 188, "atoll_id" => 18, "atoll_code" => "GDh", "latitude" => 73.136639, "longitude" => 0.221270, "name" => "Fiyoaree"),
            /**
             * 19. Gn atoll islands
             */
            array("id" => 189, "atoll_id" => 19, "atoll_code" => "Gn", "latitude" => 73.425799, "longitude" => -0.294287, "name" => "Fuvahmulah"),
            /**
             * 20. S atoll islands
             */
            array("id" => 190, "atoll_id" => 20, "atoll_code" => "S", "latitude" => 73.119106, "longitude" => -0.665054, "name" => "Maradhoo"),
            array("id" => 191, "atoll_id" => 20, "atoll_code" => "S", "latitude" => 73.233483, "longitude" => -0.582866, "name" => "Meedhoo"),
            array("id" => 192, "atoll_id" => 20, "atoll_code" => "S", "latitude" => 73.093650, "longitude" => -0.615665, "name" => "Hithadhoo"),
            array("id" => 193, "atoll_id" => 20, "atoll_code" => "S", "latitude" => 73.136387, "longitude" => -0.681034, "name" => "Feydhoo"),
            array("id" => 194, "atoll_id" => 20, "atoll_code" => "S", "latitude" => 73.230504, "longitude" => -0.588981, "name" => "Hulhudhoo"),
            array("id" => 195, "atoll_id" => 20, "atoll_code" => "S", "latitude" => 73.125882, "longitude" => -0.673394, "name" => "Maradhoo Feydhoo"),
            
        );

        $modifiedIslands = array_map(function($item) use ($datetime) {
            $item['created_at'] = $datetime;
            $item['updated_at'] = $datetime;
            return $item;
        }, $islands);

        Island::insert($modifiedIslands);

        $allIslands = Island::all();

        $allIslands->each(function($island) {
            $atoll = Atoll::find($island->atoll_id);
            $island->update(['full_name' => $atoll->name . ' ' . $island->name]);
        });
    }
}
